var universal_abilities = [{
    name: "Beads",
    id: "BEADS",
    description: "You can create any number of beads, though you can only control a number equal to twice your Heart Edge. This does not require an action, but can only be done on your turn. Abilities marked with [Extended] involve an extended effect, and the beads used still count against your maximum controlled. You can accept an amount of Stress to:\n Ignore the limit on beads controlled for one Stress per round per bead.\n Create beads on somebody else's turn, at the cost of two Stress per bead. If you accept three additional Stress per bead, you can then use a single ability that uses beads and would normally require your action.",
    source: "any",
    type: "universal",
}, {
    name: "Flight",
    id: "FLIGHT",
    description: "You can “swim” through the shinsu, effectively flying. You can only do this when your Heart is greater than one-fifth the current floor. You need to use a bead to begin using this ability, but not to continue using it. While flying in this way, you are Hindered on Brawl and Move rolls.",
    source: "any",
    type: "universal",
}, {
    name: "Shinsu Reinforcement [Extended]",
    id: "SHINSU_REINFORCEMENT_[EXTENDED]",
    description: "You can use one bead and, for two rounds, act as though your Agility and Might were increased by an amount equal to your Heart. Using this requires an action. The bonus increases those attributes for all purposes, including bonus dice, automatic successes, Edges, and your maximum Injuries and Fatigue. By accepting Stress, you can increase the duration by one round per Stress. You can accept Stress to extend the duration on other rounds, not just the first; doing so does not require an action. Additionally, you can accept one Stress (per round) to instead act as though your Agility and Might were increased by twice your Heart instead. By using one additional bead (but without accepting any additional Stress), you can additionally reinforce one object you're holding to let it function as a weapon. This lasts for up to one round after you let go of it or until the entire effect ends, whichever comes first. While you're reinforcing the object, it has Structure and Toughness equal to half your Heart and acts as an appropriate weapon for all purposes (discuss with your GM what weapon would be appropriate).",
    source: "any",
    type: "universal",
}, {
    name: "Superhuman Speed",
    id: "SUPERHUMAN_SPEED",
    description: "While you're boosted by Shinsu Reinforcement, you can accept an amount of Fatigue equal to twice your Agility Edge to take two actions in the same round. In order to buy this ability, your Agility must be at least 50.",
    source: "any",
    type: "universal",
}, {
    name: "Superhuman Strength",
    id: "SUPERHUMAN_STRENGTH",
    description: "While you're boosted by Shinsu Reinforcement, you can accept a number of Injuries equal to twice your Might Edge to perform a feat of strength. Until the end of your turn, you make any Might-based rolls with three times as many dice. In order to buy this ability, your Might must be at least 50.",
    source: "any",
    type: "universal",
}, {
    name: "Give it Everything",
    id: "GIVE_IT_EVERYTHING",
    description: "Once per week, you can accept one Exhaustion to briefly ignore your wounds. For the next thirty seconds (three rounds of combat), you cannot die by any means. Additionally, during that time being Weakened or Anxious does not Hinder your rolls and exceeding your limits on any type of Harm does not cause you to faint, collapse, break down, or die. After the round is over, you experience all the normal consequences of having Exhaustion, as well as any other Harm you may have accumulated.",
    source: "any",
    type: "universal",
}, {
    name: "Long Life",
    id: "LONG_LIFE",
    description: "Exposure to shinsu and the conditions in which you've trained have kept you from aging. You cannot take this ability unless you have an attribute that's at least 50.",
    source: "any",
    type: "universal",
}, {
    name: "Compression",
    id: "COMPRESSION",
    description: "Either by making a contract with the Administrator, or by using your own power, you can reduce your size or the size of your possessions. This is generally used when you or your weapons are too big to fit in most structures. Compressing yourself or an item requires a minute of concentration. Reversing this does not take an action. If applied to an object, anyone can reverse the effect, even without this ability. While compressed, you are Hindered on all Might rolls. Compressing a crocodile causes them to lose the Big ability while compressed. This ability uses shinsu.",
    source: "any",
    type: "universal",
}, {
    name: "Up Close and Personal",
    id: "UP_CLOSE_AND_PERSONAL",
    description: "When you buy this ability, you can get any one of the following abilities at no extra cost:\nDisarm (Fisherman), Counterattack (Fisherman), Flurry (Fisherman), Support Fighter (Scout), or Opening (Scout). You can only buy this ability twice.",
    source: "any",
    type: "universal",
}, {
    name: "Heal",
    id: "HEAL",
    description: "You can use any number of beads to repair a person's body. Each bead heals them of Injuries equal to your Heart Edge, or Fatigue equal to half your Heart Edge (rounded down). This requires ten seconds (one round of combat) per bead, but does not require an action. If you have the Magnify ability, you can increase the effectiveness of each round of healing—by using three beads, you can apply the healing benefits of two of them in one round. The additional bead cost increases linearly; tripling the effective healing speed requires five beads total, quadrupling requires seven beads total, etc. For the math nerds, the cost of healing with speed X is equal to 2X-1.",
    source: "any",
    type: "universal",
}, {
    name: "Dual Training",
    id: "DUAL_TRAINING",
    description: "When you're wielding two or more weapons at once, add a number of dice equal to your Might Edge or Agility Edge to all attack rolls. This applies before calculating the effects of Hindered.",
    source: "any",
    type: "universal",
}, {
    name: "Many-Weapon Training",
    id: "MANY-WEAPON_TRAINING",
    description: "When you're wielding more than two weapons at once, your attacks are Hindered and Impaired equal to the total number of attacks, instead of the normal penalty. You must have Dual Training to get this ability.",
    source: "any",
    type: "universal",
}, {
    name: "Titan's Grip",
    id: "TITAN'S_GRIP",
    description: "You can wield a two-handed weapon in one hand without penalties, as though it was a one-handed weapon.",
    source: "any",
    type: "universal",
}, {
    name: "Sharp as Broken Glass",
    id: "SHARP_AS_BROKEN_GLASS",
    description: "When your mind broke, the edges were left sharper. Increase your Edges by the number of Traumas you have. \nIt's not a good idea to refer to any traumatized person as broken. If you feel like you're broken, please find a therapist.",
    source: "any",
    type: "universal",
}]
var fisherman_abilities = [{
    name: "Called Shot",
    id: "CALLED_SHOT",
    description: "Before you make a Brawl roll, Throw roll, or roll with the Shot ability (or any other ability that seems applicable), you can reduce your total dice by some amount to target a specific part of your enemy or their person. The penalty amount increases with the target's Tier. If you hit, you resolve the roll as normal and may also cause your enemy to suffer an additional effect. If you're using Rapid Shot, Shot, or another ability that allows you to make multiple attacks on separate targets, you can use these attacks to target multiple parts of the same enemy. \nArm: -(Tier) dice. The enemy is Hindered on Brawl rolls with that arm for the next two rounds. \nChest: -(Tier) dice. The enemy is Hindered on Agility rolls for the next two rounds. \nEye: -(5*Tier) dice. The enemy is Blinded for the next two rounds. \nHand: -(3*Tier) dice. The enemy is disarmed and is Hindered on Brawl rolls with that hand for the next two rounds. \nHead: -(3*Tier) dice. The enemy is Hindered on Wits rolls for the next two rounds. \nHeart: -(5*Tier) dice. The enemy takes additional Unresisted Injuries equal to their Might Edge. If your attack would leave them Fragile or worse, they die. \nLeg: -(Tier) dice. The enemy is Slowed for the next round unless they are flying. \nNeck: -(5*Tier) dice. The enemy can't speak for the next two rounds. If your attack would cause them to take at least as many Injuries as half their Might (after applying Resistance and other reductions), they die. \nVitals: -(3*Tier) dice. The enemy is Hindered on all rolls for the next round. \nArmor/Shield: -(Tier) dice. The enemy can't attempt to block this attack. \nWeapon: -(2*Tier) dice. The enemy can attempt to block this, but must choose another item to take the attack instead.",
    source: "any",
    type: "fisherman",
}, {
    name: "Disarm",
    id: "DISARM",
    description: "With two stunts and by accepting two Injuries on a Brawl attack, you can knock an enemy's weapon out of their hands. It flies in a random direction and lands within Close range. That enemy can retrieve it on their turn. If your enemy has more than one weapon, you can use additional stunts and accept additional Injuries to disarm them of multiple weapons.",
    source: "position",
    type: "fisherman",
}, {
    name: "Bruiser",
    id: "BRUISER",
    description: "Add a number of dice equal to your Might Edge to your Brawl rolls.",
    source: "position",
    type: "fisherman",
}, {
    name: "Damage Sponge",
    id: "DAMAGE_SPONGE",
    description: "You can accept one Stress and one Confusion to heal yourself of a number of Injuries equal to your Might Edge. You cannot use this while Dying. You can only use this once per turn.",
    source: "position",
    type: "fisherman",
}, {
    name: "Reel",
    id: "REEL",
    description: "You can use a reel, a length of cord or cable that attaches to one end of your weapon. By using shinsu to stiffen or manipulate the line, you can control the weapon almost like you were holding it. While using a reel, you can use Brawl (and any associated stunts) at range, though you are Hindered on these rolls. The Reel has a maximum range of Medium.",
    source: "position",
    type: "fisherman",
}, {
    name: "Defender",
    id: "DEFENDER",
    description: "When one of your allies in your reach is about to get attacked, you can choose to throw yourself in front of the attack and willingly take that hit instead of them. You can't choose to dodge or avoid the attack—however, you can attempt to block it. You have to see the attack coming in order to do this.",
    source: "position",
    type: "fisherman",
}, {
    name: "Unmoving",
    id: "UNMOVING",
    description: "If an enemy's attack would move you from your position, knock you down, or in any other way move you against your will, you can accept one Injury instead.",
    source: "position",
    type: "fisherman",
}, {
    name: "Counterattack",
    id: "COUNTERATTACK",
    description: "When struck by a melee attack, you can choose to double the initial Damage Base of the attack (before applying either Resistance or effects like the Crocodile Regular's Sharp, but after applying any stunts) to make an immediate counterattack against the enemy that hit you. You cannot apply the effects of any Weapon Skills, Sunder, Opening, Flurry, dual wielding, or Called Shot to this attack. This does not apply to an attack you block. If you have Bloodied Berserker or any similar ability, calculate your attack before applying damage from the enemy's attack.",
    source: "position",
    type: "fisherman",
}, {
    name: "Reserves of Strength",
    id: "RESERVES_OF_STRENGTH",
    description: "By taking two Confusion and Stress per round, you can ignore the effects of the Weakened and Fragile conditions.",
    source: "position",
    type: "fisherman",
}, {
    name: "Flourish",
    id: "FLOURISH",
    description: "Your stylish attacks inspire your allies. You can take one Confusion to treat a Brawl attack as though it was a Reach Out roll that gets half as many successes. It still counts as a Brawl roll for attacking an enemy.",
    source: "position",
    type: "fisherman",
}, {
    name: "Challenger",
    id: "CHALLENGER",
    description: "On your turn, you can make a Manipulate roll (with a number of bonus dice equal to your Resistance Edge) against an enemy's Wits to force them to exclusively attack you for one minute (six combat rounds). If you fail this roll, you take an amount of Confusion equal to your Might Edge. This does not require your action.",
    source: "position",
    type: "fisherman",
}, {
    name: "Living Wall",
    id: "LIVING_WALL",
    description: "Whenever an enemy attempts to move past you and passes through your melee range, you can take two Fatigue and make an attack against them. If you hit, they must immediately end their movement. You cannot apply the effects of Weapon Skills, Sunder, Opening, Flurry, dual wielding, or Called Shot to this attack.",
    source: "position",
    type: "fisherman",
}, {
    name: "Bloodied Berserker",
    id: "BLOODIED_BERSERKER",
    description: "When making a Brawl roll, add half the number of Injuries you currently have to your Might for the purposes of determining the number of dice you roll and the damage you deal.",
    source: "position",
    type: "fisherman",
}, {
    name: "Flurry",
    id: "FLURRY",
    description: "If you hit with a melee attack, you can accept two Injuries to immediately make another attack, which is Impaired 2 and has -1 automatic success. You can keep this up as long as you keep hitting and taking Harm. The penalties stack for each attack.",
    source: "position",
    type: "fisherman",
}, {
    name: "Overwhelming Force",
    id: "OVERWHELMING_FORCE",
    description: "In order to buy this ability, either your Might or Resistance must be at least 50. When you make a Brawl roll, reroll all 1s. You may reroll them as many times as necessary to stop rolling 1s.",
    source: "position",
    type: "fisherman",
}]
var lightbearer_abilities = [{
    name: "Brains",
    id: "BRAINS",
    description: "Add your Wits Edge to your Think rolls.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Smooth Talker",
    id: "SMOOTH_TALKER",
    description: "Add your Wits Edge to your Manipulate rolls.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Calculator",
    id: "CALCULATOR",
    description: "Your Lighthouses can add half their dice bonus (rounded down, minimum 1 per Lighthouse) on any of your Think rolls.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Lighthouse Flow Control",
    id: "LIGHTHOUSE_FLOW_CONTROL",
    description: "With a Think roll against an enemy's Resistance, you can temporarily slow or pin them. With one success over their Resistance, you Slow them for one round. You can use a stunt to increase the duration by a round. Alternatively, you can use three times as many stunts (three as the base, plus three for each round past the first) to instead pin them for the duration. This uses your action. The enemy must be within Short range of one of your Lighthouses. This ability uses shinsu.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Emerald Sword",
    id: "EMERALD_SWORD",
    description: "You use the Lighthouse to gather shinsu around a melee weapon, boosting its power. Roll Think and add as many successes as you roll to the next attack with that weapon. For each round that passes between using this ability and making the attack, the number of successes decreases by one (minimum 0). This ability does not stack with any other uses of Emerald Sword; only the use that would grant the most successes remains. Using this ability requires your action. This ability uses shinsu.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Lighthouse Teleportation",
    id: "LIGHTHOUSE_TELEPORTATION",
    description: "You can accept one Confusion to teleport up to one person (or a similar mass of objects) between two Lighthouses you control. This requires an action. The person must be close enough to touch the Lighthouse. If the person does not want to be teleported, you make a Think roll against their Resistance and accept two additional Confusion. This ability uses shinsu.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Instant Teleport",
    id: "INSTANT_TELEPORT",
    description: "If you have the Lighthouse Teleportation ability, you can accept one additional Confusion (two total) to use the ability without using your action. Additionally, you can accept three additional Confusion (five total) to use the ability on someone else's turn. The cost is then multiplied by the number of times you've used this ability this round (plus one). I.e. if it's the first time you're using it, no multiplier.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Steer",
    id: "STEER",
    description: "You can use one or more Lighthouses to assist a ranged weapon, allowing that weapon's wielder to be much more accurate than they would be otherwise. When an ally makes a Throw roll, you can simultaneously make a Think roll and give all of your successes to your ally. They treat your successes as though they had rolled them. Using this ability gives you Confusion equal to your Wits Edge. You can use this ability when it isn't your turn, but it consumes your next action. This ability uses shinsu.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Hack",
    id: "HACK",
    description: "You can use a Lighthouse to hack into a Lighthouse that you don't control. The other Lighthouse must be within the range of yours. To hack it, you make a Think roll against the other Light Bearer's Think. If you win, you gain control of their Lighthouse and can access any data stored inside. This requires one full round of hacking. If they attempt to regain control of their Lighthouse (requiring another full round), they make another contested Think roll.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Unparalleled Insight",
    id: "UNPARALLELED_INSIGHT",
    description: "When speaking with someone and neither of you is in combat, you automatically know if they're lying or hiding something (but not necessarily what), with no roll required.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Light Wall",
    id: "LIGHT_WALL",
    description: "You can take one Confusion per Lighthouse (with a minimum of three) to form a wall with them. This requires your action to make, but not to maintain. The maximum distance between two adjacent Lighthouses is equal to one-tenth the range of said Lighthouses. While the walls between Lighthouses must be straight, the overall structure can have any number of angles—provided you control enough Lighthouses. Each section of wall has a Toughness equal to your Wits Edge and a Structure equal to your Heart Edge, both of which are multiplied by the number of Lighthouses used. While they're creating a wall, you can't use any of those Lighthouses. This ability uses shinsu.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Mystery Sphere",
    id: "MYSTERY_SPHERE",
    description: "By using a Lighthouse of at least rank B, your Lighthouse can create a large honeycomb sphere around a single enemy. Using this requires an action. Each of the interior surfaces of this sphere will, when touched, warp the enemy to a random other surface. At the beginning of each of the enemy's turns, roll Think; the Structure of the sphere during that turn is equal to ten times the number of successes on your roll. The Toughness of the sphere is equal to your Wits. Your Lighthouse must be within Close range of the chosen enemy. This ability uses shinsu.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Masterful Plan",
    id: "MASTERFUL_PLAN",
    description: "When something goes in an unexpected direction, you can declare that all is going according to plan and flashback to earlier, when you prepared for this by (for example) laying traps, gathering supplies, or in any other way preparing for your current situation.  In order to use this, you accept an amount of Confusion equal to twice your Wits Edge.",
    source: "position",
    type: "lightbearer",
}, {
    name: "Overwhelming Mind",
    id: "OVERWHELMING_MIND",
    description: "In order to buy this ability, either your Wits or Heart must be at least 50. When you make a Think roll, reroll all 1s. You may reroll them as many times as necessary to stop rolling 1s.",
    source: "position",
    type: "lightbearer",
}]
var scout_abilities = [{
    name: "Advanced Observer",
    id: "ADVANCED_OBSERVER",
    description: "Adds the following abilities to the Observer. These abilities can't be used unless you possess an advanced Observer.\n Create a hologram up to human size within Close range. This hologram can move and is virtually indistinguishable from an imitated object or person. This ability can be used in conjunction with the basic ability to play recorded audio. The hologram does not have any physical substance. The hologram fools anyone who observes it unless they attempt to physically touch it.\n Slow creatures in a small cone for one round (this requires your action). The creatures must be within Close range.\n Counter the above slowing ability (this does not need to be done on your turn, but leaves you Hindered on any rolls taken as part of your next action).\n Support the weight of a single person",
    source: "position",
    type: "scout",
}, {
    name: "Black Fish [Extended]",
    id: "BLACK_FISH_[EXTENDED]",
    description: "You can block the light around you, essentially becoming invisible. This uses your action when you start it, but not to continue using it. This requires using one bead per minute. If you don't have any beads, you can't use this ability. While invisible, sneaking using Finesse does not use an action. Any attempts to detect you are Hindered. Anyone targeting you is treated as Blinded unless they can pinpoint your position (with a successful Think roll), in which case they are Hindered.",
    source: "position",
    type: "scout",
}, {
    name: "Sneaky",
    id: "SNEAKY",
    description: "Add your Agility Edge to your Finesse rolls.",
    source: "position",
    type: "scout",
}, {
    name: "Speedy",
    id: "SPEEDY",
    description: "Add your Agility Edge to your Move rolls.",
    source: "position",
    type: "scout",
}, {
    name: "Support Fighter",
    id: "SUPPORT_FIGHTER",
    description: "You can use Agility for Brawl rolls. Damage is still based on your Might Edge.",
    source: "position",
    type: "scout",
}, {
    name: "Opening",
    id: "OPENING",
    description: "You can roll Brawl to force an enemy off-balance. You do not deal damage by default with this roll. Instead, you can give any number of your successes to the next person to attack the enemy before that enemy's next turn.. They treat these successes as though they had rolled them for all purposes. This uses your action.",
    source: "position",
    type: "scout",
}, {
    name: "Feather Foot",
    id: "FEATHER_FOOT",
    description: "By taking one Fatigue per round, you can stand, run, and otherwise move on liquid surfaces.",
    source: "position",
    type: "scout",
}, {
    name: "Spider Foot",
    id: "SPIDER_FOOT",
    description: "By taking two Fatigue per round, you can stand, run, and otherwise move on vertical surfaces or while upside down. You need to have Feather Foot before getting this ability.",
    source: "position",
    type: "scout",
}, {
    name: "On Guard",
    id: "ON_GUARD",
    description: "If it is physically possible for you to notice a nearby enemy or ambush, you do so. If the enemy or ambusher is within Short range, you don't need to roll. If they're within Medium range, you must still roll Think against their Finesse. If the hiding enemy or ambusher is a Scout or has the Sneaky ability, you must still roll Think against their Finesse. If they're using Black Fish, you are not Hindered on that roll. For every minute that you're around a hiding enemy or ambusher, you can attempt to reroll a failed Think roll you made as part of this ability.",
    source: "position",
    type: "scout",
}, {
    name: "Flow Like Water",
    id: "FLOW_LIKE_WATER",
    description: "When you roll to dodge an attack from an enemy with a lower Agility than your own, you do not take a penalty on later rolls to dodge.",
    source: "position",
    type: "scout",
}, {
    name: "Sneak Attack",
    id: "SNEAK_ATTACK",
    description: "When you attack an enemy that isn't expecting your attack (they must either be unaware of your presence or consider you friendly), your attack deals double damage.",
    source: "position",
    type: "scout",
}, {
    name: "Fall Silently",
    id: "FALL_SILENTLY",
    description: "When you attack an enemy that isn't expecting your attack (they must either be unaware of your presence or consider you friendly), your combat doesn't make any noise until the end of your target's turn (if they survive that long). This is considered a shinsu effect, but does not require a bead.",
    source: "position",
    type: "scout",
}, {
    name: "Track",
    id: "TRACK",
    description: "You can look around a space and identify traces of past events. Roll Think; the number of successes you get is equal to the maximum number of hours passed since those events. If you take 5 Confusion, the number of successes you get is instead equal to the maximum number of days since those events. If someone is deliberately attempting to conceal or falsify their tracks, they roll Finesse and subtract their successes from yours.",
    source: "position",
    type: "scout",
}, {
    name: "Overwhelming Speed",
    id: "OVERWHELMING_SPEED",
    description: "In order to buy this ability, either your Agility or Wits must be at least 50. When you make a Move roll, reroll all 1s. You may reroll them as many times as necessary to stop rolling 1s.",
    source: "position",
    type: "scout",
}]
var spearbearer_abilities = [{
    name: "Stabber",
    id: "STABBER",
    description: "When using a spear or ranged weapon in melee, you increase your Brawl by an amount of dice equal to either your Agility Edge or Might Edge. Regardless of which one you choose, you still deal damage according to your Might.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Strong Arms",
    id: "STRONG_ARMS",
    description: "You can use Might for Throw instead of Agility.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Rapid Shot",
    id: "RAPID_SHOT",
    description: "As an action, you can roll Throw and divide your successes between any number of targets. You accept one Fatigue per attack you make with this ability.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Critical Shot",
    id: "CRITICAL_SHOT",
    description: "As an action, you can make a single ranged attack that deals double damage. When you use this, you accept an amount of Fatigue equal to your Agility Edge.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Aim",
    id: "AIM",
    description: "As an action, you can take careful aim. Your next Throw roll before the end of your next turn is made with twice as many dice as normal. This does not double any automatic successes you might have. If an effect would make you Hindered on a Throw roll, this negates that Hindered effect instead.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Get Over Here",
    id: "GET_OVER_HERE",
    description: "With a lucky throw, you can snag your target and pull them towards you. If you have a reel and a weapon with projectiles at least the size of an arrow, you can attach the reel to a projectile and fire it at an enemy. This is a normal Throw attack with no other modifiers, but cannot be used with Rapid Shot, Bending Spear Technique, or Called Shot. You can then use stunts to pull the target closer to you; four stunts to move them one range increment, twelve stunts to move them two increments, twenty-eight stunts to move them three increments, or sixty stunts to move them four increments.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Get Over There",
    id: "GET_OVER_THERE",
    description: "With a good arm and a little strain, you can throw allies about as well as weapons. If you have an ally and a weapon with projectiles at least the size of an arrow, you can attach the ally to a projectile and fire it wherever you want. This does not require a roll, but has a maximum range of one increment lower than your weapon's normal range.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Sight Without Eyes",
    id: "SIGHT_WITHOUT_EYES",
    description: "You can accept an amount of Confusion equal to your Wits Edge to ignore the Blinded Condition for a single ranged attack.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Disabling Shot",
    id: "DISABLING_SHOT",
    description: "You can make an attack with a ranged projectile weapon that sticks in an opponent's joints, muscles, or other important area. Until they use their entire turn to remove the projectile, they are Impaired on all rolls with a single attribute, decided when you make the attack (e.g. they could be Impaired on all Agility-based rolls). The magnitude of the Impaired effect is equal to twice your Agility Edge.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Delayed Shot",
    id: "DELAYED_SHOT",
    description: "You can set up a reel and a ranged weapon as a trap. When setting this up, roll an attack with the weapon, roll Think, and name a circumstance that will set off the attack. If someone else wants to find a trap afterwards, they have to roll Think against your initial Think roll. You automatically find any trap that you previously set. You cannot use Critical Shot, Aim, Bending Spear Technique, Lightning Strike, or any other ability that would cause you to accept Harm or use beads as part of the attack. The trap is immune to all conditions. The maximum number of traps you can have set up at once is equal to your Wits Edge.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Bending Spear Technique",
    id: "BENDING_SPEAR_TECHNIQUE",
    description: "By taking three Confusion, you can hit an enemy with a ranged attack even if you don't have a clear shot at that enemy. This can also get around the effects of Defender.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Focused Shot",
    id: "FOCUSED_SHOT",
    description: "When making a Throw attack, you can increase your Might Edge by half of your Wits Edge for the purposes of dealing damage.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Sniper",
    id: "SNIPER",
    description: "You can choose to treat the range increment of any ranged weapon you use as though it was one step higher—Close to Short, etc.",
    source: "position",
    type: "spearbearer",
}, {
    name: "Overwhelming Accuracy",
    id: "OVERWHELMING_ACCURACY",
    description: "In order to buy this ability, either your Might or Agility must be at least 50. When you make a Throw roll, reroll all 1s. You may reroll them as many times as necessary to stop rolling 1s.",
    source: "position",
    type: "spearbearer",
}]
var wavecontroller_abilities = [{
    name: "Precision",
    id: "PRECISION",
    description: "Add your Heart Edge to your Attune rolls.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Shinsu Wall [Extended]",
    id: "SHINSU_WALL_[EXTENDED]",
    description: "Use one or more beads to create a wall of energy, enough to block a hallway, that lasts one round. This requires using an action. It's impenetrable and has Structure and Toughness equal to your Heart Edge. You can create it anywhere within Short range. For each bead, you can choose one of the following options: \nThe wall deals a number of Injuries equal to your Heart Edge (minus their Resistance Edge) to anyone adjacent to it at the start of their turn. If you use an additional bead, the range of this effect increases to Close. \nIt slows anyone adjacent to it. If you use an additional bead, the range of this effect increases to Close. \nIncrease the Structure and Toughness by your Heart Edge. This requires one bead for the first use, two beads for the second, three beads for the third, and so on. \nIt lasts up to five rounds, or until you dismiss it (does not take an action, can only be done on your turn). Each additional bead gets another five rounds. \nThe wall's negative effects don't affect those you specify (up to a number of people equal to half your Heart). This includes the ability to pass through it without first breaking it.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Quick Shield [Extended]",
    id: "QUICK_SHIELD_[EXTENDED]",
    description: "Use one or more beads to create a shield of shinsu. This can either take the form of a battle-ready shield, which can be used to block attacks (using your Attune instead of your Brawl), or a larger barrier to protect you and others from damaging large-scale attacks. In the first case, the shield does not require use of a hand and lasts until destroyed or dispelled, and has Structure and Toughness equal to half your Heart Edge times the number of beads used. In the second case, this ability requires using at least as many beads as the number of people you're protecting, lasts until the end of your next turn (unless destroyed or dispelled), cannot affect anyone outside Short range, and has Structure and Toughness equal to your Heart Edge times the number of beads used. This does not require an action. If you use this on somebody else's turn, you accept three Stress and Fatigue.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Quick Weapon [Extended]",
    id: "QUICK_WEAPON_[EXTENDED]",
    description: "Use one or more beads to create a weapon from shinsu. This can take the form of any weapon, but does not have any special abilities. The weapon grants an amount of bonus dice equal to half the number of beads (rounded down), 10 Structure per bead, and 5 Toughness per bead. If your weapon can be used for both melee and ranged attacks, it only grants half the bonus dice to each type of roll (rounded up). This does not require an action. If you use this on somebody else's turn, you accept three Stress and Fatigue.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Flare Wave Explosion",
    id: "FLARE_WAVE_EXPLOSION",
    description: "Touch an enemy (requiring a Brawl or Move roll) and roll Attune (using a bead) against their Resistance to deal Unresisted Injuries equal to your Heart Edge per success. You can simultaneously use an additional bead (and roll Attune again, though you are Hindered this time) to avoid taking the same damage. You can use this entire ability with one action. You only need one success (not counting automatic successes) on the second Attune roll.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Reverse Flow Control [Extended]",
    id: "REVERSE_FLOW_CONTROL_[EXTENDED]",
    description: "Use one bead (requiring an Attune roll against the target's Resistance) to paralyze an enemy within Close range for one round. You can target Observers or Lighthouses using this; instead of rolling against your target's Resistance, you roll against their effective Agility (determined by their controller's Agility or Wits, respectively). If you successfully hit an Observer or Lighthouse, it's inoperable for one round and cannot move or have any abilities used through it. This uses your action. You can use stunts to extend the duration, at two stunts per round. You can use additional beads to extend the duration as well, at two beads per round. You cannot add beads afterwards.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Shot",
    id: "SHOT",
    description: "You can shoot any number of beads at one or more enemies (dividing the beads as you wish between them). This requires an Attune roll (roll once per enemy), and can be dodged or blocked. If you can't see your target, you fail the roll. Treat this as a Throw roll with Damage Base equal to your Heart Edge minus each enemy's Resistance Edge. You cannot use more successes on a target than the number of beads you used on that target. This is a ranged weapon with a range of Short. Shooting a bead consumes it. This requires your action. Increasing the range counts as increasing the casting range of this ability.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Magnify",
    id: "MAGNIFY",
    description: "Any ability you have that uses beads can be altered to reach farther, cover a wider area, or—in some cases—magnify the effect. \nCasting range: Abilities that do not, by default, include the caster in their area of effect or extend from the caster have a casting range. Using one additional bead, you can extend the casting range from your reach to Close. From Close to Short requires three beads, Short to Medium requires five beads, and Medium to Long requires 10 beads. You can increase by more than one step; to do so, add the additional bead costs together. Thus extending the casting range of an ability from Short to Long requires 15 beads. Abilities that require contact cannot have their casting range increased, unless they have some other way to increase the range to one of the normal increments. \nArea: If an ability would normally affect an area within reach, you can increase it to affect Close range by using three additional beads. You can increase the area from Close to Short range with seven additional beads, from Short to Medium range with 15 additional beads, and from Medium to Long range with 30 additional beads. Increases by more than one increment function the same as they do for casting range. Abilities that do not normally have an area of effect cannot gain one with this ability. \nDuration: For abilities that do not specify other ways to increase the duration, you can use any number of beads to increase the duration by the same number of rounds. You can do this at any point during the duration to increase it further, provided you're within the unaltered casting range. \nEffect: Some abilities may specify that they can have additional or different effects if you have this ability.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Dispel",
    id: "DISPEL",
    description: "You can use a bead and make an Attune roll against an enemy's Attune to counter one shinsu-based effect they created. This uses your action. You have to either be within Short range of the effect or the creator. If you accept two Stress, you can use this on someone else's turn. Abilities that use beads automatically use shinsu.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "All-Encompassing Sight",
    id: "ALL-ENCOMPASSING_SIGHT",
    description: "Using an action, you can detect anyone within Short range who is capable of using shinsu, as well as their approximate direction. You can always tell when shinsu is being manipulated. You can even approximately tell where. You still need to roll to know what exactly is happening.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Concussive Blast",
    id: "CONCUSSIVE_BLAST",
    description: "Using an action, you can use any number of beads to throw enemies away from you. This requires an Attune roll against their Resistance; if targeting more than one enemy, roll once and apply to each enemy's Resistance. You need at least one bead per enemy. This throws enemies back one range increment (within reach to Close, Close to Short, etc). If you have the Magnify ability, you can use more beads to throw them further—double the bead cost per enemy (including required beads for affecting further-away enemies) to throw them back two range increments, triple it to throw them back three range increments, and quadruple it if you need to throw someone from melee range to Long range.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Territory",
    id: "TERRITORY",
    description: "By taking time to circulate your shinsu around the area, you can designate that area as your territory. While taking time in this way, you cannot use shinsu for any other purpose, nor can you engage in any activities that require concentration. The area remains your territory until you leave it and remain outside for at least as long as you took originally (i.e. if you took ten minutes to declare it your territory, it takes ten minutes to stop being your territory once you leave). Within that area, you gain bonus dice that apply to all Attune rolls, as well as Move, Finesse, Throw, and Brawl rolls while under the effects of Shinsu Reinforcement. The number of bonus dice, as well as the size of the area, are determined by the amount of time you take.\nOne minute: Within your reach. +1 die\nTen minutes: Close range. +5 dice\nOne hour: Short range. +10 dice\nOne day: Medium range. +25 dice\nOne month: Long range. +50 dice\nOne year: The entire floor. +100 dice",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Essence Drain",
    id: "ESSENCE_DRAIN",
    description: "Touch an enemy (requiring a Brawl or Move roll) and roll Attune (using a bead) against their Resistance to transfer up to two Stress per success from you to them. You cannot use more successes than you used beads. You cannot give them more Stress than you currently have. This requires an action.",
    source: "position",
    type: "wavecontroller",
}, {
    name: "Overwhelming Control",
    id: "OVERWHELMING_CONTROL",
    description: "In order to buy this ability, either your Heart or Agility must be at least 50. When you make an Attune roll, reroll all 1s. You may reroll them as many times as necessary to stop rolling 1s.",
    source: "position",
    type: "wavecontroller",
}]
var human_abilities = [{
    name: "Trained",
    id: "TRAINED",
    description: "You increase all of your attributes by one.",
    source: "race",
    type: "human",
}, {
    name: "Climber",
    id: "CLIMBER",
    description: "Whenever you go up a floor, you gain experience equal to half the floor (round down).",
    source: "race",
    type: "human",
}, {
    name: "Why We Keep Going",
    id: "WHY_WE_KEEP_GOING",
    description: "You have a dream of some sort. Whenever you make progress towards this dream (other than going up the tower), gain experience equal to the highest floor you've reached. You can change your dream up to once per floor. When you do, you don't gain any experience the next time you make progress towards your dream. Changing your dream causes you to gain one Exhaustion. If you achieve your dream, you retire permanently. Suggestions for your dream:\n Someone I do/don't know killed my family/friends/lover. I need to get revenge.\n My family looks down on me. I need to prove to them what I can do.\n My friend/lover/family member went up the tower. I need to find them.\n This Tower isn't right. I want to change things.\n Someone I love is determined to climb the Tower. I'm going with them. If you want to choose this Dream, or one like it, discuss it with the other players (Regulars only). With their permission, choose one that this Dream applies to.\n [Partway up the tower] These are my friends now. I'm protecting them.",
    source: "race",
    type: "human",
}, {
    name: "Savings",
    id: "SAVINGS",
    description: "Start with 5,000 credits.",
    source: "race",
    type: "human",
}, {
    name: "Adaptable",
    id: "ADAPTABLE",
    description: "You don't start with this ability, but can buy it with experience as though it was a universal ability. Humans can survive and thrive anywhere—blazing heat, freezing cold, toxins, predators, hazards, anywhere. You become immune to all poisons. You can survive in temperatures where most anyone else would freeze solid or burst into flame. You can go without food, water, or sleep for as long as you need to.",
    source: "race",
    type: "human",
}]
var crocodile_abilities = [{
    name: "Tough",
    id: "TOUGH",
    description: "You increase your Might and Resistance scores by 3. When you spend experience to increase either of these attributes, you increase that attribute by your Tier plus one.",
    source: "race",
    type: "crocodile",
}, {
    name: "Big",
    id: "BIG",
    description: "You're unnaturally large. Your melee reach is twice a normal person's reach. However, you are Hindered on all Finesse rolls.",
    source: "race",
    type: "crocodile",
}, {
    name: "Sharp",
    id: "SHARP",
    description: "You have claws. If you choose to use them, your Brawl attacks have their initial Damage Base increased by 1.These do not count as weapons.",
    source: "race",
    type: "crocodile",
}, {
    name: "Live to Hunt",
    id: "LIVE_TO_HUNT",
    description: "Each time you fight a single opponent (i.e. fighting multiple at one time does not qualify), you gain experience equal to half their highest attribute (rounded down). This only applies once per person per month.",
    source: "race",
    type: "crocodile",
}, {
    name: "Doesn't Hunt Money",
    id: "DOESN'T_HUNT_MONEY",
    description: "Start with 2,000 credits.",
    source: "race",
    type: "crocodile",
}, {
    name: "Feral",
    id: "FERAL",
    description: "You don't start with this ability, but can buy it with experience as though it was a universal ability. Any Harm you deal while Fragile, Weakened, Anxious, or Volatile is increased by half (rounded down).",
    source: "race",
    type: "crocodile",
}]
var canine_abilities = [{
    name: "Born Fighter",
    id: "BORN_FIGHTER",
    description: "You increase your Might, Resistance, and Agility scores by 2. When you spend experience to increase any of these attributes, you increase that attribute by your Tier plus one.",
    source: "race",
    type: "canine",
}, {
    name: "Implanted Weakness",
    id: "IMPLANTED_WEAKNESS",
    description: "Any attempt to influence or control your mental state to any degree automatically succeeds.",
    source: "race",
    type: "canine",
}, {
    name: "Not Down Yet",
    id: "NOT_DOWN_YET",
    description: "Every time you become Fragile (maximum once per day) or gain an Exhaustion or Trauma, you gain experience equal to the highest floor you've reached. Additionally, taking strenuous actions while Fragile does not cause you to gain an Injury. You can continue to act normally while Dying; any strenuous actions while Dying still cause you to accept an Injury. You are immune to any instant-death effects of Called Shots.",
    source: "race",
    type: "canine",
}, {
    name: "Transformation ",
    id: "TRANSFORMATION_",
    description: "You gain access to the Canine family's set of abilities. You need to purchase all of these abilities, as normal.",
    source: "race",
    type: "canine",
}, {
    name: "Sink or Swim",
    id: "SINK_OR_SWIM",
    description: "Start with 2,000 credits.",
    source: "race",
    type: "canine",
}]
var silverdwarf_abilities = [{
    name: "The Path Forward",
    id: "THE_PATH_FORWARD",
    description: "When facing a decision of some sort, you can accept an amount of Confusion equal to your Wits Edge to roll Think and ask one question for every two successes.\n Which way is safest?\n Which way is fastest?\n What challenges lie in this direction?\n Any similar question about the immediate future.",
    source: "race",
    type: "silverdwarf",
}, {
    name: "Pathfinder",
    id: "PATHFINDER",
    description: "Whenever you help someone find the correct path or help them with their journey, gain experience equal to their highest attribute minus the greatest type of Harm they currently have (minimum 1). This can only apply once per person per floor.",
    source: "race",
    type: "silverdwarf",
}, {
    name: "Support of Your People",
    id: "SUPPORT_OF_YOUR_PEOPLE",
    description: "Start with 10,000 credits.",
    source: "race",
    type: "silverdwarf",
}, {
    name: "Jury-Rig",
    id: "JURY-RIG",
    description: "You don't start with this ability, but can buy it with experience as though it was a universal ability. Sometimes you have to make do with junk. Given an hour or two, plus access to a decent amount of supplies, you can put together a tool or machine that can get the job done. One job, at least. Whatever you create doesn't grant bonus dice.",
    source: "race",
    type: "silverdwarf",
}]
var redwitch_abilities = [{
    name: "Where Fate Leads",
    id: "WHERE_FATE_LEADS",
    description: "You can accept an amount of Stress equal to half your Heart (rounded up) to roll Attune and ask one question for every two successes.\n What should I do to achieve my goal?\n How can I get to my destination?\n How dangerous is this path?\n Any similar question about the future.",
    source: "race",
    type: "redwitch",
}, {
    name: "Guide",
    id: "GUIDE",
    description: "Whenever you guide someone where they need to go, and whenever a Regular changes their Dream because of you (directly or indirectly), gain experience equal to the total number of Harms they have. Calculate this after the Regular takes the Exhaustion for changing their Dream. Whenever someone takes Exhaustion or Trauma, or enters Weakened, Fragile, Anxious, or Volatile status because of advice or help you gave, gain experience equal to the Harms they have.",
    source: "race",
    type: "redwitch",
}, {
    name: "Gifts",
    id: "GIFTS",
    description: "Start with 10,000 credits.",
    source: "race",
    type: "redwitch",
}, {
    name: "Cassandra's Truth",
    id: "CASSANDRA'S_TRUTH",
    description: "You don't start with this ability, but can buy it with experience as though it was a universal ability. The more profound your words are, the more people distrust them. You can choose to take only half the normal Stress (rounded up) to use Where Fate Leads. Whatever answers you get, you have to convince others (with a Manipulate or Reach Out roll against their Think) for them to believe the truth of what you say.",
    source: "race",
    type: "redwitch",
}]
var noble_abilities = [{
    name: "Nepotism",
    id: "NEPOTISM",
    description: "You start off with up to two D-rank items, or any one C-rank item.",
    source: "race",
    type: "noble",
}, {
    name: "Allowance",
    id: "ALLOWANCE",
    description: "Every week, you receive 300 credits times the highest floor you've reached (e.g after reaching floor 10 you receive 3,000 per week).",
    source: "race",
    type: "noble",
}, {
    name: "Frowned Upon",
    id: "FROWNED_UPON",
    description: "If you attack any member of your noble family and the family finds out, you're disowned and stop getting your allowance.",
    source: "race",
    type: "noble",
}, {
    name: "Bloodline",
    id: "BLOODLINE",
    description: "You can purchase a unique ability, depending on your family. When you make your character, choose a family to belong to. You gain their name and are allowed to purchase their ability.",
    source: "race",
    type: "noble",
}, {
    name: "You Have Your Parents' Fire",
    id: "YOU_HAVE_YOUR_PARENTS'_FIRE",
    description: "Each family has an associated shinsu quality. If you ever gain the Shinsu Quality universal ability, any quality except the one associated with your family costs twice as much experience.",
    source: "race",
    type: "noble",
}, {
    name: "Making the Family Proud",
    id: "MAKING_THE_FAMILY_PROUD",
    description: "The family you choose has an experience trigger. You gain that ability for free.",
    source: "race",
    type: "noble",
}, {
    name: "Wealth",
    id: "WEALTH",
    description: "Start with 20,000 credits.",
    source: "race",
    type: "noble",
}]
var heir_abilities = [{
    name: "Royal Blood",
    id: "ROYAL_BLOOD",
    description: "Increase all of your attributes by three. Whenever you spend experience to increase one of your attributes, you increase that attribute by your Tier plus one. Start at Tier 2. You reach Tier 3 at the same time as the other races—after spending 5,000 experience.",
    source: "race",
    type: "heir",
}, {
    name: "Competition",
    id: "COMPETITION",
    description: "Whenever you defeat another Heir or ensure they won't be a competitor, you gain experience equal to three times their highest attribute.",
    source: "race",
    type: "heir",
}, {
    name: "Rich",
    id: "RICH",
    description: "Start with 50,000 credits.",
    source: "race",
    type: "heir",
}, {
    name: "Watch Your Back",
    id: "WATCH_YOUR_BACK",
    description: "You don't start with this ability, but can buy it with experience as though it was a universal ability. All Harm you deal to another Royal Heir is doubled.",
    source: "race",
    type: "heir",
}]
var irregular_abilities = [{
    name: "Learn by Doing",
    id: "LEARN_BY_DOING",
    description: "When you are hit by a shinsu attack, you can choose to treat the damage from that as Unresisted and gain experience equal to the Harm you take.",
    source: "race",
    type: "irregular",
}, {
    name: "Shake the Foundations of the Tower",
    id: "SHAKE_THE_FOUNDATIONS_OF_THE_TOWER",
    description: "Whenever you shake the status quo, you gain experience:\n Equal to the current floor for a tiny or temporary change.\n Equal to twice the current floor for a significant and long-lasting change.\n Equal to three times the current floor for a total upheaval.",
    source: "race",
    type: "irregular",
}, {
    name: "Rapid Growth",
    id: "RAPID_GROWTH",
    description: "Increasing to Tier 2 happens at 250 experience instead of 500. Increasing to each further Tier multiplies the required total experience by 5 instead of by 10; 1,250 and 6,250 instead of 5,000 and 50,000.",
    source: "race",
    type: "irregular",
}, {
    name: "Surprisingly Durable",
    id: "SURPRISINGLY_DURABLE",
    description: "At the beginning of the game, set your Resistance to 10.",
    source: "race",
    type: "irregular",
}, {
    name: "Enter Alone",
    id: "ENTER_ALONE",
    description: "Start with no money.",
    source: "race",
    type: "irregular",
}, {
    name: "Starting Small",
    id: "STARTING_SMALL",
    description: "During character creation, you do not receive free points to increase your attributes.",
    source: "race",
    type: "irregular",
}, {
    name: "Natural Control",
    id: "NATURAL_CONTROL",
    description: "You don't start with this ability, but can buy it with experience as though it was a universal ability. You do not need to sign a contract to control shinsu.",
    source: "race",
    type: "irregular",
}]
var keene_abilities = [{
    name: "Cold-Hearted",
    id: "COLD-HEARTED",
    description: "Whenever you make a Wits-based roll, you automatically gain successes equal to your Wits Edge in addition to any you would gain from other sources. Whenever you make a Heart-based roll, you are Impaired by an amount equal to your Heart Edge.",
    source: "family",
    type: "keene",
}]
var trumbald_abilities = [{
    name: "Crafter",
    id: "CRAFTER",
    description: "You can create and refine items. Creating them requires materials costing half of the item's price. Improving them requires materials costing one-tenth of the item's price. Either use requires a full day. When you do this, make a Finesse or Think roll. The number of required successes is determined by the rank: making or improving an E-rank item requires five successes; a D-rank item requires ten successes; a C-rank item requires twenty successes; a B-rank item requires fifty successes; an A-rank item requires 100 successes; and a S-rank item requires two hundred successes. You can use stunts to: increase the Toughness by 1, increase the Structure by 2, increase the amount of bonus dice the item grants by 1, or decrease the time required to one-half of what it was (the first usage of this stunt reduces the time to eight hours, the second reduces the time to four hours, etc). If you do not have enough successes on this roll, you recover materials equal to half of what you invested.",
    source: "family",
    type: "trumbald",
}]
var haas_abilities = [{
    name: "Strongest Body",
    id: "STRONGEST_BODY",
    description: "When you use Shinsu Reinforcement, you increase your Might and Agility by an amount equal to one and a half times your Heart (rounded down) instead of an amount equal to your Heart. While taking Stress to increase the bonus, you add three times your Heart instead of twice.",
    source: "family",
    type: "haas",
}]
var lemarque_abilities = [{
    name: "Capture",
    id: "CAPTURE",
    description: "You can use your action and accept Stress equal to twice your Heart Edge to attempt to exert your will over a divine fish within Short range. Make an Attune roll against the fish's Resistance (this roll is Impaired by an amount equal to their Heart plus their Wits if used against an intelligent creature). If you succeed, you have complete control over that fish for as long as you want, until either you fall unconscious for any reason, someone else uses this ability on the fish (which uses a Attune roll against your Attune), or you choose to release the fish.",
    source: "family",
    type: "lemarque ",
}]
var halleck_abilities = [{
    name: "Made of Granite",
    id: "MADE_OF_GRANITE",
    description: "When you first take this ability, double your Resistance. Anything that would increase your Resistance (including spending experience) increases it by twice as much.",
    source: "family",
    type: "halleck ",
}]
var posada_abilities = [{
    name: "Analysis",
    id: "ANALYSIS",
    description: "Through sheer intelligence, you've managed to partially replicate the essential ability of a Guide. You can ask the GM any one question. If you have the minimum information necessary to reach an answer through logic and thought, the GM answers you and you accept Confusion equal to your Wits Edge. If you don't have enough information, you accept Confusion equal to half your Wits Edge (round up).",
    source: "family",
    type: "posada ",
}]
var aven_abilities = [{
    name: "Family Swordsmanship",
    id: "FAMILY_SWORDSMANSHIP",
    description: "Through intense training and the revelation of some family secrets, your sword has stopped being a physical object, and is instead a shinsu-based manifestation of your skill and bloodlust. You can create a shinsu sword by taking one Stress. This does not require an action and does not need to happen on your turn. Bonuses that would normally only apply when wielding a physical sword apply when wielding your shinsu sword. Because your sword no longer has a physical form, it isn't as bound by the rules of reality, and tends to hit its target every time. Your attacks with the shinsu sword cannot be dodged by anyone with an Agility lower than your Heart, nor can they be blocked with anything that does not protect your target's entire body (e.g. a suit of armor would protect them, while an armor inventory would not). Your Damage Base with this is equal to your Might Edge plus half your Heart Edge. Your shinsu sword functions as both a blade and a needle for the purposes of Weapon Skills and other abilities.",
    source: "family",
    type: "aven",
}]
var yanetta_abilities = [{
    name: "Shrouded in Flame",
    id: "SHROUDED_IN_FLAME",
    description: "You can accept one Stress per round to become engulfed in your own fire. All enemies within your reach at the end of each of your turns, or who attack you in melee (this applies for each attack), take Injuries equal to your Heart Edge minus their Resistance Edge (minimum 1). While this is active you increase your Resistance by an amount equal to twice your Heart Edge. This doesn't require an action to activate, but must be activated on your turn.",
    source: "family",
    type: "yanetta",
}]