/* 
="{
        id: ""&A2&"",
        name: ""&B2&"",
        range: ""&C2&"",
        level: ""&D2&"",
        use: ""&E2&""
        description: ""&F2&""
    },"

    
="{
        id: @"&A2&"@,
        name: @"&B2&"@,
        range: @"&C2&"@,
        level: @"&D2&"@,
        use: @"&E2&"@,
        description: @"&F2&"@
    },"

 */


INVESTIGATOR_ABILITIES = [{
    id: "CAREFUL_OBSERVATION",
    name: "Careful Observation",
    tier: 1,
    cost: "1 Intellect point",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You take a minute to examine your surroundings. If you succeed at a difficulty 4 perception task, you take note of an inanimate object within an immediate distance that is related to your current investigation. You see a particular color of mud on some boots, a loose thread in a coat on a hook, the disturbance of dust on a bookshelf that reveals the most recently examined book, or some other detail that another person would have likely passed over. If there is no such detail in the area, you learn that too(and know that you can move on, as there’s nothing of note there). If there are two or more such details, you still just make one roll; you learn one detail if you succeed at a difficulty 4 task, a second detail if you succeed at a difficulty 5 task, the third detail if you succeed at a difficulty 6 task, and so forth.",
},
{
    id: "DECIPHER",
    name: "Decipher",
    tier: 1,
    cost: "1 Intellect point",
    context: "Action to initiate;",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "If you spend one minute examining a piece of writing or code in a language you don’t understand, you can make an Intellect roll to get the gist of the message. The difficulty is usually 3 but may be higher based on the complexity of the language or code.\nAction to initiate; one minute to complete.",
},
{
    id: "FLEET_OF_FOOT",
    name: "Fleet of Foot",
    tier: 1,
    cost: "1+ Speed points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "Instead of being able to move an immediate distance as part of another action, you can move a short distance as part of anotherInstead of moving a short distance as your entire action for a turn, you can move a long distance. If you apply a level of Effort to this ability, you can move a long distance and make an attack as your entire action for a turn, but the attack is hindered.",
},
{
    id: "FOLLOW_THE_TRAIL",
    name: "Follow the Trail",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "When you apply Effort to a perception or tracking task because you are attempting to find a specific person or place, you can apply a free level of Effort.",
},
{
    id: "KNOWLEDGE_SKILLS",
    name: "Knowledge Skills",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You are trained in two skills in which you are not already trained. Choose two areas of knowledge such as history, geography, forensics, and so on. You can select this ability multiple times. Each time you select it, you must choose two different skills.",
},
{
    id: "MISSING_DETAIL",
    name: "Missing Detail",
    tier: 1,
    cost: "2 Intellect points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You listen to the words of an NPC, read a transcript of something that was said, or read an account written by someone—such as a statement—and you immediately note something that wasn’t said. This can be something implied by what was said or written, or something obviously left out. The GM provides this brief fact to you. The words written or spoken must be substantial, like someone giving an eyewitness account, telling a story, or—as previously mentioned—giving a statement.",
},
{
    id: "OPERATE_IN_THE_DARK",
    name: "Operate in the Dark",
    tier: 1,
    cost: "1 Intellect point",
    context: "Action to initiate.",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "For the next hour, you use your other senses to compensate for a lack of vision. If you’re blinded or just in the dark, you operate without any hindrance.",
},
{
    id: "READY_FOR_DANGER",
    name: "Ready for Danger",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You are trained in initiative.",
},
{
    id: "SURGING_CONFIDENCE",
    name: "Surging Confidence",
    tier: 1,
    cost: "1 Might point",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You can use your one - action recovery roll as part of another action.",
},
{
    id: "ESCAPE",
    name: "Escape",
    tier: 2,
    cost: "2 Speed points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You slip your restraints, squeeze through the bars, break the grip of the creature holding you, pull free from sucking quicksand, or otherwise get loose from whatever is holding you in place.",
},
{
    id: "EYE_FOR_DETAIL",
    name: "Eye for Detail",
    tier: 2,
    cost: "2 Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "When you spend at least five minutes thoroughly exploring an area no larger than a short distance in diameter, you can ask the GM one question about the area and get an answer. You cannot use this more than one time per area per 24 hours.\nAction to initiate; five minutes to complete",
},
{
    id: "HAND_TO_EYE",
    name: "Hand to Eye",
    tier: 2,
    cost: "2 Speed points",
    context: "Action to initiate.",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "This ability provides an asset to any tasks involving manual dexterity, such as pickpocketing, lockpicking, games involving agility, and so on, for one minute.",
},
{
    id: "JUST_A_HUNCH",
    name: "Just a Hunch",
    tier: 2,
    cost: "2 Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "A flash of insight provides you with a small clue or suggests a course of action with regard to an urgent question, problem, or obstacle you’re facing when you have no idea how to proceed. Once you use this ability, you can’t use it again until after your next ten - hour recovery roll, and then only if you’ve followed up on the clue or course of action suggested by your last hunch.",
},
{
    id: "RESEARCH",
    name: "Research",
    tier: 2,
    cost: "2 Intellect points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "If you spend at least two hours with an appropriate source of information(such as the internet, a library, the archives, or a single informative book), you learn one relevant fact about a topic you choose. Essentially, you ask the GM a question and they give you an answer appropriate for the topic based on the source. The internet or a small - town library might not have accurate esoteric occult information, while a book on ancient architecture might have everything you need on that topic.",
},
{
    id: "SKILL_WITH_DEFENSE",
    name: "Skill With Defense",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in defense tasks of that type.",
},
{
    id: "SKIM",
    name: "Skim",
    tier: 2,
    cost: "2 Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "Taking just a minute, you can skim through a book, a computer database, a diary, an accounting ledger, or a similar information source and get the gist of the contents. If you succeed at a difficulty 4 Intellect - based task, you also learn a prominent or surprising bit of information you didn’t already know. \nAction to initiate; one minute to complete",
},
{
    id: "SURVEILLANCE",
    name: "Surveillance",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "All tasks involving monitoring, watching, or tailing a person or place are eased. This includes setting up cameras, microphones, or other equipment.",
},
{
    id: "TRAVEL_SKILLS",
    name: "Travel Skills",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You are trained in two skills in which you are not already trained. Choose two of the following: driving, endurance, geography, piloting, or riding. You can select this ability multiple times. Each time you select it, you must choose two different skills.",
},
{
    id: "INTERACTION_SKILLS",
    name: "Interaction Skills",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You are trained in two skills in which you are not already trained. Choose two of the following: deception, discerning motive, intimidation, or persuasion. You can select this ability multiple times. Each time you select it, you must choose two different skills.",
},
{
    id: "QUICK_RECOVERY",
    name: "Quick Recovery",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "Your ten - minute recovery roll is only a single action.",
},
{
    id: "SCARRED_AND_HARDENED",
    name: "Scarred and Hardened",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You reduce the Stress you suffer from physical injury by 1.  You still suffer Stress from mental shock or despair normally.",
},
{
    id: "SEEN_SOME_STUFF",
    name: "Seen Some . . .  Stuff",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You reduce the Stress you suffer from mental shock or despair by 1.  You still suffer Stress from physical injury normally.",
},
{
    id: "SKILL_WITH_ATTACKS",
    name: "Skill With Attacks",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "Choose one type of attack in which you are not already trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are trained in attacks using that type of weapon. You can select this ability multiple times. Each time you select it, you must choose a different type of attack.",
},
{
    id: "THINK_YOUR_WAY_OUT",
    name: "Think Your Way Out",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You can use points from your Intellect Pool rather than your Might Pool or Speed Pool on any noncombat action.",
},
{
    id: "TRAPFINDER",
    name: "Trapfinder",
    tier: 3,
    cost: "3+ Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You find any traps(like a floor that would give way beneath you) or mechanical triggers to a trap or defense system that might pose a threat. You can do this without setting them off and in lieu of making a roll to find them. This ability automatically finds traps of level 4 or below. You can use Effort to increase the level of traps that can be found by 2, so using two levels of Effort can find all traps of level 8 and below.",
},
{
    id: "UNNATURAL_DREAM",
    name: "Unnatural Dream",
    tier: 3,
    cost: "3 Intellect points + 3 Stress",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "When you fall asleep, you have a dream that provides insight into a situation you currently face(although you do not consciously choose the topic).  The GM provides you with the information you learn, probably details you couldn’t learn conventionally.",
},
{
    id: "CREDIBLE_HYPOTHESIS",
    name: "Credible Hypothesis",
    tier: 4,
    cost: "4 Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You examine an immediate area(basically an average room) and learn precise, useful details about the past(if any exist).  You can ask the GM up to four questions about the immediate area; each requires its own roll(the GM determines the difficulty, but the default is level 4).",
},
{
    id: "HEIGHTENED_SKILLS",
    name: "Heightened Skills",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You are trained in two tasks of your choosing(other than attacks or defense). If you choose a task you’re already trained in, you instead become specialized in that task. You can’t choose a task you’re already specialized in.",
},
{
    id: "LOOK_FOR_THE_TELL",
    name: "Look for the Tell",
    tier: 4,
    cost: "4 Intellect points",
    context: "Action to initiate",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "After spending at least a minute with a person in conversation, for the next minute you know when they are lying.",
},
{
    id: "PERFECT_TRACKER",
    name: "Perfect Tracker",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "If you find a set of tracks, you can follow them without error unless the conditions absolutely prohibit it(heavy rain, complete darkness, etc. ).",
},
{
    id: "SUBTLE_STEPS",
    name: "Subtle Steps",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "When you move no more than a short distance, you can move without making a sound, regardless of the surface you move across.",
},
{
    id: "TAKE_THEIR_MEASURE",
    name: "Take Their Measure",
    tier: 4,
    cost: "3 Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You learn the level of all creatures you can see. If they have any special weaknesses(such as a vulnerability to fire), you learn what those are.",
},
{
    id: "VERSATILE_MIND",
    name: "Versatile Mind",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "When you make a Speed defense roll, you can use points from your Intellect Pool instead of your Speed Pool.",
},
{
    id: "SUPERNATURAL_SENSES",
    name: "Supernatural Senses",
    tier: 4,
    cost: "4 Intellect points + 3 Stress",
    context: "Action",
    supernatural: true,
    source: "type",
    type: "INVESTIGATOR",
    description: "You have an uncanny intuition when it comes to finding things. While exploring, you can extend your senses up to 1 mile(1. 6 km) in any direction and ask the GM a very simple, general question— usually a yes - or - no question—about that area, such as “Is there a library nearby ?” or “Are there any bodies buried in that yard ?” If the answer you seek is not in the area, you receive no information.",
},
{
    id: "HARD_TO_KILL",
    name: "Hard to Kill",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You can reroll any defense task you make but never more than once per round.",
},
{
    id: "MASTERY_WITH_DEFENSE",
    name: "Mastery With Defense",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "Choose one type of defense task in which you are trained: Might, Speed, or Intellect. You become specialized in defense tasks of that type. You can select this ability up to three times. Each time you select it, you must choose a different type of defense task.",
},
{
    id: "SEIZE_THE_MOMENT",
    name: "Seize the Moment",
    tier: 5,
    cost: "4+ Speed points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "If you succeed on a Speed defense roll to resist an attack, you gain anYou can use the action immediately even if you have already taken a turn in the round. You don’t take an action during the next round, unless you apply a level of Effort when you use Seize the Moment.",
},
{
    id: "SHRUG_IT_OFF",
    name: "Shrug It Off",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You ignore the negative effects of your first Stress level.",
},
{
    id: "VIGILANT",
    name: "Vigilant",
    tier: 5,
    cost: "5 Might points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "When affected by an attack or effect that would daze or stun you, or anything that would specifically make you lose your next action, you are not affected.",
},
{
    id: "SEE_THE_PAST",
    name: "See the Past",
    tier: 5,
    cost: "5 Intellect points + 3 Stress",
    context: "Action",
    supernatural: true,
    source: "type",
    type: "INVESTIGATOR",
    description: "You touch an object, read the subtle echoes of its existence through time, ask the GM a question about the object’s past, and get a general answer. The answers are often in the form of brief images or sensations rather than specific answers in a language you know. The GM assigns a level to the question, so the more obscure the answer, the more difficult the task. Generally, knowledge that you could find by looking somewhere other than your current location is level 1, and obscure knowledge of the past is level 7.  After you use this ability, you have an asset on identifying the object.",
},
{
    id: "ADVANCED_RESEARCH",
    name: "Advanced Research",
    tier: 6,
    cost: "6 Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "Through luck, a hunch, or just general preparedness, you already researched the topic that now faces you, providing you with information and answers as if you took a full week with an appropriate source of information to learn what you could.General Knowledge",
},
{
    id: "GENERAL_KNOWLEDGE",
    name: "General Knowledge",
    tier: 6,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "All tasks involving knowledge, research, observation, or assessment are eased.",
},
{
    id: "IMPOSSIBLE_CLUE",
    name: "Impossible Clue",
    tier: 6,
    cost: "6 Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "You focus for one action on an immediate area or a single individual, after which you learn(no roll needed) a fact about that area or person that you seemingly couldn’t possibly know. Like Sherlock Holmes, you notice a detail no one else would and come to a conclusion that is always correct. The GM provides the fact(the conclusion) and then you and the GM can work together to come up with the clue. Alternatively, you can skip coming up with the specifics of the clue and just focus on the information gained.",
},
{
    id: "MASTERY_WITH_ATTACKS",
    name: "Mastery With Attacks",
    tier: 6,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "INVESTIGATOR",
    description: "Choose one type of attack in which you are trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are specialized in attacks using that type of weapon. (If you aren’t trained in an attack, select Skill With Attacks to become trained in that attack. )",
},
{
    id: "SEE_THE_FUTURE",
    name: "See the Future",
    tier: 6,
    cost: "6 Intellect points + 3 Stress",
    context: "Enabler",
    supernatural: true,
    source: "type",
    type: "INVESTIGATOR",
    description: `Based on all the variables you perceive, you can predict the next few minutes. This has the following effects:
    • For the next ten minutes, your defense rolls gain an asset.
    • You have a sort of danger sense. For the next ten minutes, you gain an asset in seeing through deceptions and attempts to betray you, as well as avoiding traps and ambushes.
    • You know what people are probably thinking and what they will say before they say it. For the next ten minutes, you gain an asset to tasks involving interaction and deception.`,
}]


var LEARNS_QUICKLY_ABILITIES = [{
    id: "ENHANCED_INTELLECT",
    name: "Enhanced Intellect",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You gain 3 points to your Intellect Pool.",
},
{
    id: "PICKED_UP_A_FEW_THINGS",
    name: "Picked Up a Few Things",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You are trained in any noncombat task in which you do not already have training.",
},
{
    id: "QUICK_STUDY",
    name: "Quick Study",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You learn from repetitive actions. You gain an asset to rolls for similar tasks after the first time(such as operating the same device or making attacks against the same foe). Once you move on to a new task, the familiarity with the old task fades—unless you start doing it again.",
},
{
    id: "ENHANCED_INTELLECT_EDGE",
    name: "Enhanced Intellect Edge",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You gain + 1 to your Intellect Edge.",
},
{
    id: "FLEX_SKILL",
    name: "Flex Skill",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "At the beginning of each day, choose one task(other than attacks or defense) on which you will concentrate. For the rest of that day, you’re trained in that task. You can’t use this ability with a skill in which you’re already trained to become specialized.",
},
{
    id: "HARD_TO_DISTRACT",
    name: "Hard to Distract",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You are trained in Intellect defense tasks.",
},
{
    id: "PAY_IT_FORWARD",
    name: "Pay It Forward",
    tier: 4,
    cost: "(3 Intellect points):",
    context: "Action",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You can pass on what you’ve learned. When you give another character a suggestion involving their next action that is not an attack, their action is eased for one minute.",
},
{
    id: "ENHANCED_INTELLECT",
    name: "Enhanced Intellect",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You gain 3 points to your Intellect Pool.",
},
{
    id: "LEARNED_A_FEW_THINGS",
    name: "Learned a Few Things",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You are trained in two areas of knowledge of your choice, or specialized in one area of knowledge of your choice.",
},
{
    id: "TWO_THINGS_AT_ONCE",
    name: "Two Things at Once",
    tier: 6,
    cost: "(6 Intellect points)",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "You divide your attention and take two separate actions this round.",
},
{
    id: "SKILL_WITH_DEFENSE",
    name: "Skill With Defense",
    tier: 6,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "focus",
    type: "LEARNS_QUICKLY",
    description: "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in defense tasks of that type",
}];


var PROTECTOR_ABILITIES = [{
    id: "COMBAT_PROWESS",
    name: "Combat Prowess",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You add 1 additional point of damage to one type of attack of your choice: melee attacks or ranged attacks. You can choose this up to two times, once for melee and once for ranged. Enabler.",
},
{
    id: "NO_NEED_FOR_WEAPONS",
    name: "No Need for Weapons",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "When you make an unarmed attack (such as a punch or kick), you deal 2 additional points of damage. Enabler.",
},
{
    id: "ONE_AGAINST_MANY",
    name: "One Against Many",
    tier: 1,
    cost: "1+ Speed points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Sometimes you’ve got to deal with a group of enemies, or even a swarm of enemies (rats, spiders, or worse). When this happens, perhaps the best you can do by yourself is control where everyone in the fight can or cannot go. You attempt an attack against the highest-level enemy, and if successful, in lieu of inflicting damage, you affect all the foes within an immediate distance in one of two ways: either they must move within an immediate area as you direct, or they are prevented from moving into a space in immediate range that you choose. You can use the latter option to keep them away from allies (as long as the allies don’t move), but you can’t keep them away from you in this way. The foes affected must be level 1, although you can spend additional points from your Speed Pool to affect higher levels, with each point increasing the affected creature level by 1. You must always affect the highest-level foe, so if you face a level 3 cultist and his thirty level 1 rats, you must spend 3 Speed points. Action.",
},
{
    id: "OTHER_KNOWLEDGE",
    name: "Other Knowledge",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You aren’t just a brute—you have other areas of interest as well. You are trained in one non-physical skill of your choosing in which you don’t already have training. Enabler.",
},
{
    id: "OVERWATCH",
    name: "Overwatch",
    tier: 1,
    cost: "1 Intellect point",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You use a ranged weapon to target a limited area (such as a doorway, a hallway, or the eastern side of a clearing) and make an attack against the next viable target to enter that area, acting just before they act. You also negate any benefit the target would have from cover, position, range, or visibility. Further, you inflict 1 additional point of damage with the attack. You can remain on overwatch as long as you wish, within reason. Action.",
},
{
    id: "PHYSICAL_SKILLS",
    name: "Physical Skills",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You are trained in endurance or gymnastics. If you are already trained in one or both, this does not improve them. Enabler.",
},
{
    id: "PROTECTOR",
    name: "Protector",
    tier: 1,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You designate a single character to be your charge. You can change this freely every round, but you can have only one charge at a time. As long as that charge is within immediate range, they gain an asset for Speed defense tasks because you have their back. Enabler.",
},
{
    id: "SLOW_THEM_DOWN",
    name: "Slow Them Down",
    tier: 1,
    cost: "1 Might or 1 Speed point",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "This is a pummeling melee attack or a covering-fire ranged attack. Your attack inflicts 1 less point of damage than normal, but it dazes your target for one round, during which time their tasks are hindered and they move only half as fast as normal. Action.",
},
{
    id: "TAKE_THE_HIT",
    name: "Take the Hit",
    tier: 1,
    cost: "2 Might points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If someone you are close enough to touch is struck and will suffer damage, you can take the hit instead. The other person suffers no damage, and you gain 3 points of Stress regardless of the damage that would have been originally dealt.",
},
{
    id: "BODYGUARD",
    name: "Bodyguard",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If you’re standing next to an ally, that ally’s initiative tasks are eased. Enabler.",
},
{
    id: "COPING_WITH_THE_IMPOSSIBLE",
    name: "Coping With the Impossible",
    tier: 2,
    cost: "2 Intellect points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "When faced with something supernatural and difficult (or impossible) to harm by any normal means, you improvise a way to use the environment or the situation to cause the target to lose its next turn if you succeed at an Intellect-based task. Once you affect a target with this ability, further attempts to use this ability on the same target are hindered. Action.",
},
{
    id: "INTIMIDATING_DEMEANOR",
    name: "Intimidating Demeanor",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You gain an asset when attempting to intimidate someone that can see you while you display a threat of violence. Enabler.",
},
{
    id: "QUICK_RECOVERY",
    name: "Quick Recovery",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Your ten-minute recovery roll is only a single action. Enabler.",
},
{
    id: "SCARRED_AND_HARDENED",
    name: "Scarred and Hardened",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You reduce the Stress you suffer from physical injury by 1. You still suffer Stress from mental shock or despair normally. Enabler.",
},
{
    id: "SKILL_WITH_ATTACKS",
    name: "Skill With Attacks",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Choose one type of attack in which you are not already trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are trained in attacks using that type of weapon. You can select this ability multiple times. Each time you select it, you must choose a different type of attack. Enabler.",
},
{
    id: "SKILL_WITH_DEFENSE",
    name: "Skill With Defense",
    tier: 2,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in defense tasks of that type. Enabler.",
},
{
    id: "STAND_WATCH",
    name: "Stand Watch",
    tier: 2,
    cost: "2 Might points",
    context: "Action to initiate",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "While standing watch (mostly remaining in place for an extended period of time), you unfailingly remain awake and alert for up to eight hours. During this time, you are trained in perception tasks as well as stealth tasks to conceal yourself from those who might approach. Action to initiate.",
},
{
    id: "SUPPORT_THE_TEAM",
    name: "Support the Team",
    tier: 2,
    cost: "2 Might points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "While you stand watch and take no other actions, allies within a short distance gain an asset to their perception tasks, as they know you’ve got their backs. Enabler.",
},
{
    id: "COMBAT_MEDIC",
    name: "Combat Medic",
    tier: 3,
    cost: " ",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You are trained in healing. Further, if a person has moved to the dead step of the damage track and you can reach them within one round, you can use your action to keep them from dying. They remain debilitated and are most likely unconscious. They will need more formal medical attention (such as in a lengthy hospital stay) to recover. Action.",
},
{
    id: "DEADLY_AIM",
    name: "Deadly Aim",
    tier: 3,
    cost: "3 Speed points",
    context: "Action to initiate",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "For the next minute, all ranged attacks you make inflict 2 additional points of damage. Action to initiate.",
},
{
    id: "LUNGE",
    name: "Lunge",
    tier: 3,
    cost: "2 Might points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You extend yourself for a powerful stab or smash. The awkward lunge hinders the attack roll. If your attack is successful, it inflicts 4 additional points of damage. Action.",
},
{
    id: "REACTION",
    name: "Reaction",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If a creature you attacked on your last turn with a melee attack uses its action to move out of immediate range, you gain an action to attack the creature as a parting blow, even if you have already taken a turn in the round. Enabler.",
},
{
    id: "SEEN_SOME_STUFF",
    name: "Seen Some ... Stuff",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You reduce the Stress you suffer from mental shock or despair by 1. You still suffer Stress from physical injury normally. Enabler.",
},
{
    id: "SPRAY",
    name: "Spray",
    tier: 3,
    cost: "2 Speed points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If a weapon has the ability to fire rapid shots without reloading (usually called a rapid-fire weapon, such as a submachine gun), you can spray multiple shots around your target to increase the chance of hitting. This ability uses 1d6 + 1 rounds of ammo (or all the ammo in the weapon, if it has less than the number rolled). If the attack is successful, it deals 1 less point of damage than normal. You can also use this ability on multiple thrown weapons (stones, shuriken, daggers, and so on) if you’re carrying them on your person or they are all within reach. Action.",
},
{
    id: "TACTICAL_PLAN",
    name: "Tactical Plan",
    tier: 3,
    cost: "3 Intellect points",
    context: "",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You put in the time to develop a strategy for an upcoming trip to a location you can study records and/or anecdotes about. If you visit afterward, you and up to five allies who accompany you—to whom you explain your plan—gain three of the following benefits (your choice) for that particular visit: • Ease their first initiative roll during the visit • Ignore the first point of Stress that would otherwise be gained during the visit • Ease their first perception roll made during the visit • Ease their first interaction roll made during the visit • Ease their first defense roll made during the visit • Ease any task to flee and/or escape the location<r> Action to initiate; one hour to devise plan.",
},
{
    id: "TOUGH",
    name: "Tough",
    tier: 3,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You can take punishment beyond what others can. You gain an additional step in your damage track between hale and impaired called hurt. Other than being one step closer to impaired, hurt imposes no changes to your character. Basically, you’re sore and bruised, but it’s nothing serious. Walk it off. Enabler.",
},
{
    id: "VIGILANCE",
    name: "Vigilance",
    tier: 3,
    cost: "2 Intellect points",
    context: "Action to initiate",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You take a cautious approach to combat, focusing more on protecting yourself than on hurting your opponents. While this ability is active, you gain an asset on Speed defense rolls, and your attacks are hindered. This effect lasts for as long as you wish, but it ends if no combat is taking place within range of your senses. Action to initiate.",
},
{
    id: "IMPOSSIBLE_STRENGTH",
    name: "Impossible Strength",
    tier: 3,
    cost: "3 Might points and 3 Stress",
    context: "Action to initiate",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "For the next minute, you possess inhuman strength. You gain an asset on any noncombat action requiring physical strength, and +2 to your Might Edge. You could lift a small car. You could toss a full file cabinet across the room. In melee combat, you inflict 4 additional points of damage. Action to initiate.",
},
{
    id: "AMAZING_EFFORT",
    name: "Amazing Effort",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Choose either Might Effort or Speed Effort. When you apply at least one level of that kind of Effort to a noncombat task, you get a free level of Effort on that task. Enabler.",
},
{
    id: "BURY_THE_BODIES",
    name: "Bury the Bodies",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You gain an asset to any action involved in covering up a crime scene, a scene of violence, a break-in, or something similar. This includes speaking with the authorities. Enabler.",
},
{
    id: "CAPABLE_FIGHTER",
    name: "Capable Fighter",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Your attacks deal 1 additional point of damage. Enabler.",
},
{
    id: "EXPERT_BODYGUARD",
    name: "Expert Bodyguard",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Once per turn, choose one ally that’s next to you; their defense tasks are eased. Enabler.",
},
{
    id: "FREE_FROM_DANGER",
    name: "Free From Danger",
    tier: 4,
    cost: "4 Might points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If you do nothing else as your action, you can grab up to two allies (conscious or otherwise, and even if they are held fast by something) and move them a short distance. For the remainder of that round, you and they have an asset on defense rolls. Action.",
},
{
    id: "MOMENTUM",
    name: "Momentum",
    tier: 4,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If you use an action to move, your next attack made using a melee weapon before the end of the next round inflicts 2 additional points of damage. Enabler.",
},
{
    id: "SIZE_THEM_UP",
    name: "Size Them Up",
    tier: 4,
    cost: "3 Intellect points",
    context: "Action to study",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You use an action to study a creature you can see. For the next 24 hours, all your attacks against them, and your defense rolls against their attacks, are eased. Action to study.",
},
{
    id: "SNIPE",
    name: "Snipe",
    tier: 4,
    cost: "2 Speed points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If you spend one action aiming, in the next round you can make a precise ranged attack. You have an asset on this attack. If your attack is successful, it inflicts 4 additional points of damage. Action.",
},
{
    id: "TOUCH_THE_UNTOUCHABLE",
    name: "Touch the Untouchable",
    tier: 4,
    cost: "4 Might points and 3 Stress",
    context: "Action to initiate",
    supernatural: true,
    source: "type",
    type: "PROTECTOR",
    description: "For one minute, you can physically interact with something that normally could not be interacted with normally or safely, like an intangible ghost or liquid magma. Action to initiate.",
},
{
    id: "ARC_SPRAY",
    name: "Arc Spray",
    tier: 5,
    cost: "3 Speed points",
    context: "Action",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If a weapon has the ability to fire rapid shots without reloading (usually called a rapid-fire weapon, such as a submachine gun), you can fire your weapon at up to three adjacent targets at once. Make a separate hindered attack roll against each target. Action.",
},
{
    id: "GOT_YOUR_BACK",
    name: "Got Your Back",
    tier: 5,
    cost: "4 Speed points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You’re constantly giving your friends a quick helping hand. If an ally within immediate distance of you fails at a physical task, including an attack or defense roll, you can immediately allow that player to reroll. If the second roll also fails, you gain 1 point of Stress. Enabler.",
},
{
    id: "IMPROVED_SUCCESS",
    name: "Improved Success",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "When you roll a 17 or higher on an attack roll that deals damage, you deal 1 additional point of damage. For instance, if you roll a natural 18, which normally deals 2 extra points of damage, you instead deal 3 extra points. If you roll a natural 20 and choose to deal damage rather than achieve a special major effect, you deal 5 extra points of damage rather than 4. Enabler.",
},
{
    id: "MASTERY_WITH_ATTACKS",
    name: "Mastery With Attacks",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Choose one type of attack in which you are trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are specialized in attacks using that type of weapon. Enabler. (If you aren’t trained in an attack, select Skill With Attacks to become trained in that attack.)",
},
{
    id: "MASTERY_WITH_DEFENSE",
    name: "Mastery With Defense",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "Choose one type of defense task in which you are trained: Might, Speed, or Intellect. You are specialized in defense tasks of that type. You can select this ability up to three times. Each time you select it, you must choose a different type of defense task. Enabler.",
},
{
    id: "PARRY",
    name: "Parry",
    tier: 5,
    cost: "5 Speed points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You can deflect incoming attacks quickly. When you activate this ability, for the next ten rounds you ease all Speed defense rolls. Enabler.",
},
{
    id: "SHRUG_IT_OFF",
    name: "Shrug It Off",
    tier: 5,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You ignore the negative effects of your first Stress level. Enabler.",
},
{
    id: "SAVAGERY",
    name: "Savagery",
    tier: 5,
    cost: "5 Might points and 3 Stress",
    context: "Action to change or change back",
    supernatural: true,
    source: "type",
    type: "PROTECTOR",
    description: "You call upon some of the most visceral, primal fears and draw power to change into a savage, inhuman beast for an hour. In this new form, you gain +8 to your Might Pool, +2 to your Might Edge, +4 to your Speed Pool, and +2 to your Speed Edge. While in beast form, you can’t spend Intellect points for any reason other than to try to change to your normal form before the one-hour duration is over (a difficulty 2 task). In addition, you attack any and every living creature within short range. After you revert to your normal form, you take a –1 penalty to all rolls for one hour. If you did not kill and eat at least one substantial creature while in beast form, the penalty increases to –2 and affects all your rolls for the next 24 hours. Eating an intelligent creature gives you 3 points of Stress. Action to change or change back.",
},
{
    id: "AGAIN_AND_AGAIN",
    name: "Again and Again",
    tier: 6,
    cost: "8 Speed points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You can take an additional action in a round in which you have already acted. Enabler.",
},
{
    id: "BEACON_OF_HOPE",
    name: "Beacon of Hope",
    tier: 6,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If you make a successful attack roll, you can choose one ally within a short distance that can see you. They are inspired by your success and their next task is eased. Enabler.",
},
{
    id: "FIGHT_ON",
    name: "Fight On",
    tier: 6,
    cost: " ",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "You do not suffer the normal penalties for being impaired on the damage track. If debilitated, instead of suffering the normal penalty of being unable to take most actions, you can continue to act; however, all tasks are hindered. Enabler.",
},
{
    id: "FINISHING_BLOW",
    name: "Finishing Blow",
    tier: 6,
    cost: "5 Might points",
    context: "Enabler",
    supernatural: false,
    source: "type",
    type: "PROTECTOR",
    description: "If your foe is prone, stunned, or somehow helpless or incapacitated when you strike, you inflict 7 additional points of damage on a successful hit. Enabler.",
},
{
    id: "SPIN_ATTACK",
    name: "Spin Attack",
    tier: 6,
    cost: "5+ Speed points",
    context: "Action",
    supernatural: true,
    source: "type",
    type: "PROTECTOR",
    description: "You stand still and make attacks against up to five foes, all as part of the same action in one round. All of the attacks have to be the same sort of attack (melee or ranged). Make a separate attack roll for each foe. You remain limited by the amount of Effort you can apply on one action. Anything that modifies your attack or damage applies to all of these attacks. In addition to the normal options for using Effort, you can use Effort to increase the number of foes you can attack with this ability (one additional foe per level of Effort used in this way). Action.",
},]

ELECUTIONIST_ABILITIES = [
    {
        id: "CONNECTED",
        name: "Connected",
        tier: 1,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You know people who get things done—not just respected people in positions of authority, but also a variety of online hackers and regular street criminals. These people are not necessarily your friends and might not be trustworthy, but they owe you a favor. You and the GM should work out the details of your contacts.",
    },
    {
        id: "DE-STRESS",
        name: "De-Stress ",
        tier: 1,
        cost: "(1 Intellect point)",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "While resting or relaxing with allies for an hour, you and they lose 1 more point of Stress than normal.",
    },
    {
        id: "ENCOURAGEMENT",
        name: "Encouragement ",
        tier: 1,
        cost: "(1 Intellect point)",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "While you maintain this ability through ongoing inspiring oration, your allies within short range ease one of the following task types (your choice): defense tasks, attack tasks, or tasks related to any skill that you are trained or specialized in.",
    },
    {
        id: "ENTHRALL",
        name: "Enthrall ",
        tier: 1,
        cost: "(1 Intellect point)",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "While talking, you grab and keep another creature’s attention, even if the creature can’t understand you. For as long as you do nothing but speak  (you can’t even move), the other creature takes no actions other than to defend itself, even over multiple rounds. If the creature is attacked, the effect ends.",
    },
    {
        id: "INNER_DEFENSE",
        name: "Inner Defense",
        tier: 1,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Life’s trials have toughened you and made you hard to read. You are trained in any task to resist another creature’s attempt to discern your true feelings, beliefs, or plans. You are likewise trained in resisting torture, telepathic intrusion, and mind control.",
    },
    {
        id: "KNOWLEDGE_SKILLS",
        name: "Knowledge Skills",
        tier: 1,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You are trained in two skills in which you are not already trained. Choose two areas of knowledge such as history, geography, psychology, and so on. You can select this ability multiple times. Each time you select it, you must choose two different skills.",
    },
    {
        id: "SECRET_AGENDAS",
        name: "Secret Agendas ",
        tier: 1,
        cost: "(1 Intellect point)",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "When speaking with at least two different NPCs for at least a minute, you pick up on subtle cues to determine one of two things (you choose): • The relationship between the NPCs (including their actual feelings about each other, at least generally). • If there are at least three NPCs, you pick the odd one out. You determine which of the group is least like the others. For example, if talking to a married couple secretly on the verge of divorce, you can pick up on subtle indications of resentment or concealed hostility. If you’re interacting with a group of people but one of them secretly works for The Web, you can pick up on something odd about them (but not specific details).",
    },
    {
        id: "UNDERSTANDING",
        name: "Understanding ",
        tier: 1,
        cost: "(1 Intellect point)",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You observe or study a creature or object. Your next interaction with that creature or object gains one asset.",
    },
    {
        id: "VERBAL_DISGUISE",
        name: "Verbal Disguise ",
        tier: 1,
        cost: "(1 Intellect point)",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You can mimic the voice and speech patterns of a person you have heard speak before, allowing you to make one significant statement. If the person you are speaking to sees you, they will not fall for the deception, so this ability is likely best used over the telephone, in the dark, or with a heavy physical disguise. You can continue to use this ability, but the cost is 1 Intellect point for each important statement you make. This ability doesn’t make you any more persuasive—it merely disguises who is speaking. If the GM rules that you’ve said something the listener simply cannot believe the mimicked speaker would say, you immediately fail; if you’ve said more than one thing, the listener knows that none of it has come from the mimicked speaker.",
    },
    {
        id: "AGITATE",
        name: "Agitate",
        tier: 2,
        cost: "2 Intellect points",
        context: "Action to initiate; five minutes to complete",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You shout at a target you can see and who can easily hear you, and on a successful Intellect-based roll, they move an immediate distance in any direction you wish (because they’re startled, they heed a fake warning, or they’re otherwise unconsciously induced to do so).",
    },
    {
        id: "COLD_READING",
        name: "Cold Reading",
        tier: 2,
        cost: "2 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "When you spend at least five minutes talking to a person, you can ask the GM one question about that person and get an answer. Alternatively, you can forgo the question and simply ease all tasks involving interaction with the person for 24 hours. You cannot use this more than one time per person per 24 hours.",
    },
    {
        id: "DEFUSE",
        name: "Defuse",
        tier: 2,
        cost: "1 Intellect point",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "During the course of an investigation, your questions sometimes elicit an angry or even violent response. Through dissembling, verbal distraction, calming words, or similar evasion, you prevent a person from attacking anyone or anything for one round, and your next interaction with them is eased.",
    },
    {
        id: "DISINCENTIVIZE",
        name: "Disincentivize",
        tier: 2,
        cost: "1 Intellect point",
        context: "Action to initiate; about an hour to complete",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "With some demoralizing words, you hinder all actions attempted by any number of targets within short range who can understand you. You choose which targets are affected. Affected targets’ actions are hindered for one round.",
    },
    {
        id: "GATHER_INTELLIGENCE",
        name: "Gather Intelligence",
        tier: 2,
        cost: "2 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "While within or near a large group of people, you can ask around about any topic you choose and come away with useful information. You can ask a specific question, or you can simply obtain general facts. You also get a good idea of the general layout of the location involved, note the presence of all major sites, and perhaps even notice obscure details. For example, not only do you find out if anyone in the neighborhood has seen the missing boy, but you also get a working knowledge of the layout of the neighborhood, note all the good hiding places, and realize that everyone seems to be leery of one old house.",
    },
    {
        id: "INSPIRE_AGGRESSION",
        name: "Inspire Aggression",
        tier: 2,
        cost: "2 Intellect points",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Your words twist the mind of a character within short range who is able to understand you, unlocking their more primitive instincts. As a result, they gain an asset on their Might-based attack rolls for one minute.",
    },
    {
        id: "INSPIRING_EASE",
        name: "Inspiring Ease",
        tier: 2,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Through stories, songs, art, or other forms of entertainment, you inspire your friends. After spending 24 hours with you, once per day each of your friends can ease one task of their choice. This benefit is ongoing while you remain in the friend’s company. It ends if you leave, but it resumes if you return to the friend’s company within 24 hours. If you leave the friend’s company for more than 24 hours, you must spend another 24 hours together to reactivate the benefit.",
    },
    {
        id: "QUICK_WITS",
        name: "Quick Wits",
        tier: 2,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "When performing a task that would normally require spending points from your Intellect Pool, you can spend points from your Speed Pool instead.",
    },
    {
        id: "SKILL_WITH_DEFENSE",
        name: "Skill With Defense",
        tier: 2,
        cost: " ",
        context: "Action to initiate or reinitiate",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in defense tasks of that type.",
    },
    {
        id: "BLEND_IN",
        name: "Blend In",
        tier: 3,
        cost: "4 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "For the next minute, you blend in—creatures still see you, but they attach no importance to your presence. While blending in, you are specialized in stealth and Speed defense tasks. This effect ends if you do something to reveal your presence or position—attacking, using an ability, moving a large object, and so on. If this occurs, you can regain the remaining period of effect by taking an action to focus on seeming innocuous and as if you belong.",
    },
    {
        id: "COMMUNICATION",
        name: "Communication",
        tier: 3,
        cost: "2 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You can convey a basic concept to a creature that normally can’t speak or understand speech. The creature can also give you a very basic answer to a simple question.",
    },
    {
        id: "GRAND_DECEPTION",
        name: "Grand Deception",
        tier: 3,
        cost: "3 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You convince an intelligent creature that can understand you and isn’t hostile of something that is wildly and obviously untrue.",
    },
    {
        id: "MIND_GAMES",
        name: "Mind Games",
        tier: 3,
        cost: "3 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You use lies and trickery, mockery, and perhaps even hateful, obscene language against a foe that can understand you. If successful, the foe is stunned for one round and cannot act, and it is dazed in the following round, during which time its tasks are hindered.",
    },
    {
        id: "ORATORY",
        name: "Oratory",
        tier: 3,
        cost: "4 Intellect points",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "When speaking with a group of intelligent creatures that can understand you and aren’t hostile, you convince them to take one reasonable action in the next round. A reasonable action should not put the creatures or their allies in obvious danger or be wildly out of character.",
    },
    {
        id: "SEEN_SOME_STUFF",
        name: "Seen Some ... Stuff",
        tier: 3,
        cost: " ",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You reduce the Stress you suffer from mental shock or despair by 1. You still suffer Stress from physical injury normally.",
    },
    {
        id: "SLIP_OF_THE_TONGUE",
        name: "Slip of the Tongue",
        tier: 3,
        cost: "3 Intellect points",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "In a conversation with an NPC, you use verbal trickery to get them to reveal an important piece of information that they were attempting to conceal. You can try to determine the topic of the information, but ultimately the GM determines what the NPC actually says.",
    },
    {
        id: "SURVEILLANCE",
        name: "Surveillance",
        tier: 3,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "All tasks involving monitoring, watching, or tailing a person or place are eased. This includes setting up cameras, microphones, or other equipment.",
    },
    {
        id: "IRRESISTIBLE_QUESTION",
        name: "Irresistible Question",
        tier: 3,
        cost: "3 Intellect points and 3 Stress",
        context: "Action",
        supernatural: true,
        source: "type",
        type: "ELECUTIONIST",
        description: "You ask a question of one creature within a short distance. If you make a successful Intellect roll, they are compelled to answer the question as truthfully and completely as they can.",
    },
    {
        id: "ANTICIPATE_ATTACK",
        name: "Anticipate Attack",
        tier: 4,
        cost: "4 Intellect points",
        context: "Action to initiate",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You can sense when and how creatures attacking you will make their attacks. Your Speed defense rolls are eased for one minute.",
    },
    {
        id: "COVER_STORY",
        name: "Cover Story",
        tier: 4,
        cost: "4 Intellect points",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "After studying (either up close or from afar) a group, organization, or individual for at least five minutes, you come up with a cover story—an elaborate lie—that the group or individual in question is very likely to believe. If you or anyone else uses the cover story, any deception, persuasion, disguise, or similar task related to the cover story is eased. This benefit lasts until the cover story is irrefutably proven false (which might never happen).",
    },
    {
        id: "HEIGHTENED_SKILLS",
        name: "Heightened Skills",
        tier: 4,
        cost: " ",
        context: "Action to initiate",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You are trained in two tasks of your choosing (other than attacks or defense). If you choose a task you’re already trained in, you instead become specialized in that task. You can’t choose a task you’re already specialized in.",
    },
    {
        id: "LOOK_FOR_THE_TELL",
        name: "Look for the Tell",
        tier: 4,
        cost: "4 Intellect points",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "After spending at least one minute with a person in conversation, you know when they are lying for the next minute.",
    },
    {
        id: "SCARRED_AND_HARDENED",
        name: "Scarred and Hardened",
        tier: 4,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You reduce the Stress you suffer from physical injury by 1. You still suffer Stress from mental shock or despair normally.",
    },
    {
        id: "SKILL_WITH_ATTACKS",
        name: "Skill With Attacks",
        tier: 4,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Choose one type of attack in which you are not already trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are trained in attacks using that type of weapon. You can select this ability multiple times. Each time you select it, you must choose a different type of attack.",
    },
    {
        id: "SPUR_EFFORT",
        name: "Spur Effort",
        tier: 4,
        cost: "5 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Choose an ally within immediate range. If that character applies Effort to a task on their next turn, they get a free level of Effort on that task.",
    },
    {
        id: "STRESS",
        name: "Stress",
        tier: 4,
        cost: "5 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Your terrifying, insidious words impose 3 points of Stress (4 points of damage on NPCs) on up to five people you choose that can hear and understand you within short range. Make separate attack rolls against each creature.",
    },
    {
        id: "UNDERSTANDING_WHY",
        name: "Understanding Why",
        tier: 4,
        cost: "4 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "If you succeed at a discerning motive task, you fully understand a person’s motives and the root causes for why they do what they do. You may not get details, but you get a fair bit of general insight. You might, for example, ascertain that a murderer has a deep-seated insecurity, or that the person helping them owed them a huge debt.",
    },
    {
        id: "TERRORIZE",
        name: "Terrorize",
        tier: 4,
        cost: "4 Might points and 3 Stress",
        context: "Action to initiate",
        supernatural: true,
        source: "type",
        type: "ELECUTIONIST",
        description: "A creature that can understand you within a short distance suffers 3 points of Stress (4 points of damage to an NPC) and spends their next action fleeing from you as quickly as they can. They will not approach you for an hour afterward unless threatened.",
    },
    {
        id: "PERFORMANCE",
        name: "Performance",
        tier: 5,
        cost: "4 Intellect points",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You let your voice become your instrument. For one hour, you speak with absolute clarity and smoothness, using any manner of tones, vocal ranges, and accents. You can even perfectly imitate the voices of whomever you choose. Anyone hearing you is impressed and positively predisposed to you. For 24 hours, you gain an asset on any interaction task involving them.",
    },
    {
        id: "SHRUG_IT_OFF",
        name: "Shrug It Off",
        tier: 5,
        cost: " ",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You ignore the negative effects of your first Stress level.",
    },
    {
        id: "SOFT_SPEECH",
        name: "Soft Speech",
        tier: 5,
        cost: "5 Intellect points",
        context: "Action ",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You convince someone to confide in you in a very short amount of time. They see you not only as a friend but as a trusted confidant. After just one minute of conversation, you need make no further rolls to get the person to tell you literally anything.",
    },
    {
        id: "STIMULATE",
        name: "Stimulate",
        tier: 5,
        cost: "6 Intellect points",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Your words encourage a creature you touch who can understand you. The next action they take is eased by three steps.",
    },
    {
        id: "THINK_YOUR_WAY_OUT",
        name: "Think Your Way Out",
        tier: 5,
        cost: " ",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You can use points from your Intellect Pool rather than your Might Pool or Speed Pool on any noncombat action.",
    },
    {
        id: "CONTROL",
        name: "Control",
        tier: 5,
        cost: "5 Intellect points and 3 Stress",
        context: "Enabler",
        supernatural: true,
        source: "type",
        type: "ELECUTIONIST",
        description: "You control the actions of a creature within a short distance who can understand you. This lasts for ten minutes or until they are out of range. If you compel them to do something they would never normally do, you must roll again to maintain your effect.",
    },
    {
        id: "INSPIRING_SUCCESS",
        name: "Inspiring Success",
        tier: 6,
        cost: "6 Intellect points",
        context: "Enabler",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "When you learn this ability, choose one of the following with your group: Might tasks, Speed tasks, or Intellect tasks. When you apply a level of Effort on a task related to that stat and you succeed on your roll, choose another character within short range. On their next turn, that character has an asset on the next task they attempt using that stat.",
    },
    {
        id: "MASTERY_WITH_DEFENSE",
        name: "Mastery With Defense",
        tier: 6,
        cost: " ",
        context: "Action to initiate",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "Choose one type of defense task in which you are trained: Might, Speed, or Intellect. You are specialized in defense tasks of that type. You can select this ability up to three times. Each time you select it, you must choose a different type of defense task.",
    },
    {
        id: "SOOTHING_WORDS",
        name: "Soothing Words",
        tier: 6,
        cost: "6 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "A creature that you speak with for at least ten minutes loses all of their accumulated Stress.",
    },
    {
        id: "TRUE_COMMUNICATION",
        name: "True Communication",
        tier: 6,
        cost: "6 Intellect points",
        context: "Action",
        supernatural: false,
        source: "type",
        type: "ELECUTIONIST",
        description: "You establish a bond with one person or creature so uncanny that you can make yourself understood even if you don’t share a language. Further, you can communicate on just one sensory level if that’s all you have (if they can just see you but not hear you, or hear you but not see you) without any loss of understanding. Once this bond is established, it never goes away. You can bond with only one person or creature at a time.",
    },
    {
        id: "CONDEMN",
        name: "Condemn",
        tier: 6,
        cost: "6 Intellect points and 3 Stress",
        context: "Enabler.",
        supernatural: true,
        source: "type",
        type: "ELECUTIONIST",
        description: "Drawing upon dark forces, you relegate one person to a future of endless despair by telling them something truly horrifying about themselves (true or not) that they henceforth believe deep in their core. They lose their next action, and all their actions afterward are hindered by two steps. Most people thus affected flee if possible.",
    },
]

OCCULTIST_ABILITIES = [
    {
        id: "ALREADY_TAINTED",
        name: "Already Tainted",
        tier: 1,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You begin the game with access to abilities considered supernatural.Such abilities are marked with ⧌. Check with the GM to make certain that this is appropriate for the campaign.",
    },
    {
        id: "ARTEFACT_AFFINITY",
        name: "Artefact Affinity",
        tier: 1,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "Any tasks in which you identify or use an artefact are eased.",
    },
    {
        id: "ESOTERIC_SKILLS",
        name: "Esoteric Skills",
        tier: 1,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "Your background has led you down many strange rabbit holes.Choose two of the following skills in which you are not already trained: biology, history, identifying, philosophy, physics, publishing, religion, or researching. You become trained in these two skills.",
    },
    {
        id: "INTUITION",
        name: "Intuition",
        tier: 1,
        cost: "2 Intellect points",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You get a weird feeling when something is not quite right. You don’t choose when this ability works—the GM does, telling you to spend the Intellect points and giving you a clue as to what feels wrong. The GM might tell you that something feels bad about opening the door at the end of the hallway, that the man in the hat reminds you of a terrible dream you had, or that the child you’re looking for is no longer nearby. The GM does not have to trigger this ability, and in fact it should be a surprising but occasional insight rather than an always-available ability you can rely on. If you don’t have the points to spend to activate this ability, it doesn’t work.",
    },
    {
        id: "SENSITIVE",
        name: "Sensitive",
        tier: 1,
        cost: "1 Intellect point",
        context: "Action to initiate.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "For the next ten minutes, your tasks to perceive abnormal presences or influences are eased (including those that are usually imperceptible to regular people or animals).",
    },
    {
        id: "SLIGHTLY_SINISTER_SKILLS",
        name: "Slightly Sinister Skills",
        tier: 1,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You are trained in two skills in which you are not already trained. Choose two of the following: deception, disguise, intimidation, pickpocketing, or stealth. You can select this ability multiple times. Each time you select it, you must choose two different skills.",
    },
    {
        id: "SUPERNATURAL_COMPREHENSION",
        name: "Supernatural Comprehension",
        tier: 1,
        cost: "2 Intellect points",
        context: "Action to initiate.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You identify the parameters of an unnatural effect within an immediate distance, like a curse, the presence of something inhuman, or a spell. This typically requires at least a minute of study and reflection.",
    },
    {
        id: "UNDERSTANDING",
        name: "Understanding",
        tier: 1,
        cost: "1 Intellect point",
        context: "Action.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You observe or study a creature or object. Your next interaction with that creature or object gains one asset.",
    },
    {
        id: "VENTRILOQUISM",
        name: "Ventriloquism",
        tier: 1,
        cost: "1 Intellect point",
        context: "Action.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "For one round, you make it seem as though your voice is coming from somewhere of your choosing within an immediate distance.",
    },
    {
        id: "MESMERISM",
        name: "Mesmerism",
        tier: 1,
        cost: "1 Intellect point and 1 Stress",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You transfix a person within an immediate distance. The target loses their next action and is unaware of anything that happens during the round unless they are attacked or otherwise shaken out of it. In the following round, they are disoriented and all their actions are hindered.",
    },
    {
        id: "COLD_READING",
        name: "Cold Reading",
        tier: 2,
        cost: "2 Intellect points",
        context: "Action to initiate; five minutes to complete.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "When you spend at least five minutes talking to a person, you can ask the GM one question about that person and get an answer. Alternatively, you can forgo the question and simply ease all tasks involving interaction with the person for 24 hours. You cannot use this more than one time per person per 24 hours.",
    },
    {
        id: "HOAX",
        name: "Hoax",
        tier: 2,
        cost: "2 Intellect points",
        context: "Action to initiate.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "With at least ten minutes of preparation, you can use common materials to perpetrate a brief but surprisingly believable fake event. The event lasts only about one round and should be very simple and mostly visual. A frightening shadow lurks in the doorway, a figure runs off into the night, you chop off your finger with a knife, and so on. Typically, if the person you’re trying to fool is far away (but can still see your hoax), the task is eased.",
    },
    {
        id: "PRACTICED_WITH_MEDIUM_WEAPONS",
        name: "Practiced With Medium Weapons",
        tier: 2,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You can use light and medium weapons without penalty. If you wield a heavy weapon, attacks with it are hindered.",
    },
    {
        id: "SEEN_SOME_..._STUFF",
        name: "Seen Some ... Stuff",
        tier: 2,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You reduce the Stress you suffer from mental shock or despair by 1. You still suffer Stress from physical injury normally.",
    },
    {
        id: "SKILL_WITH_DEFENSE",
        name: "Skill With Defense",
        tier: 2,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in defense tasks of that type.",
    },
    {
        id: "SPOUT_NONSENSE",
        name: "Spout Nonsense",
        tier: 2,
        cost: "2+ Intellect points",
        context: "Action.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You can fast-talk your way through any conversation involving the occult or the paranormal, using confusing terms and strange synchronistic logic loops that confound even others with knowledge of the subject. The person that you are speaking to stands bewildered and befuddled, unable to take an action for one round. For each additional Intellect point you spend, you can attempt to affect another person with the same gibberish, but they must all be within an immediate distance of you.",
    },
    {
        id: "PREMONITION",
        name: "Premonition",
        tier: 2,
        cost: "2 Intellect points",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You learn one random fact about a creature, object, or location that is pertinent to a topic you designate. Alternatively, you can choose to learn a creature’s level; however, if you do so, you cannot learn anything else about it later with this ability.",
    },
    {
        id: "SEND_THOUGHTS",
        name: "Send Thoughts",
        tier: 2,
        cost: "2+ Intellect points and 2 Stress",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You mentally transmit a message to someone you know well. The message can be up to ten words or it can be an image of your devising. The recipient must be within 1 mile (1.6 km), but for every additional point of Intellect you spend, this distance is increased by another mile.",
    },
    {
        id: "COOPERATIVE_SORCERY",
        name: "Cooperative Sorcery",
        tier: 3,
        cost: "4 Intellect points",
        context: "Action.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You know a little about magic. If someone stands next to you and uses a supernatural power, you can boost that power by increasing the range by one category, doubling the number of targets, or easing the task for it to take effect. In addition to the Intellect point cost for activating this ability, if the ability you’re helping with causes the user Stress, you suffer the same Stress as them.",
    },
    {
        id: "EMBRACING_THE_UNKNOWN",
        name: "Embracing the Unknown",
        tier: 3,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "Interaction tasks with supernatural beings are eased.",
    },
    {
        id: "INTENSE_PRACTITIONER",
        name: "Intense Practitioner",
        tier: 3,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "If you apply at least one level of Effort to a task involving the supernatural, you get a free level of Effort on that task.",
    },
    {
        id: "PEERING_BEYOND_THE_VEIL",
        name: "Peering Beyond the Veil",
        tier: 3,
        cost: "3 Intellect points and 3 Stress",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You become aware of supernatural activity that you couldn’t otherwise perceive. You can see invisible creatures or objects and hear inaudible sounds within a short distance for one hour, and you can get a sense of any supernatural activities that have occurred within that area in the last 24 hours.",
    },
    {
        id: "RESISTANCE_TO_THE_UNCANNY",
        name: "Resistance to the Uncanny",
        tier: 3,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "The ill effects of using artefacts are mitigated somewhat. You gain 1 less point of Stress than normal when using an artefact.",
    },
    {
        id: "SHATTER",
        name: "Shatter",
        tier: 3,
        cost: "2+ Intellect points and 3 Stress",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You mystically cause the detonation of an object you choose within long range. The object must be a small, mundane item composed of homogeneous matter (such as a coffee cup, a doorknob, a rock, and so on). The object explodes in an immediate radius, dealing 1 point of damage to all creatures and objects in the area. If you apply Effort to increase the damage, you deal 2 additional points of damage per level of Effort (instead of 3 points); targets in the area take 1 point of damage even if you fail the attack roll.",
    },
    {
        id: "SUPERNATURAL_RESISTANCE",
        name: "Supernatural Resistance",
        tier: 3,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "Your defense tasks against supernatural effects are eased.",
    },
    {
        id: "COMBATING_THE_UNCANNY",
        name: "Combating the Uncanny",
        tier: 4,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "All your attacks against supernatural beings are eased.",
    },
    {
        id: "HEIGHTENED_SKILLS",
        name: "Heightened Skills",
        tier: 4,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You are trained in two tasks of your choosing (other than attacks or defense). If you choose a task you’re already trained in, you instead become specialized in that task. You can’t choose a task you’re already specialized in.",
    },
    {
        id: "SHRUG_IT_OFF",
        name: "Shrug It Off",
        tier: 4,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You ignore the negative effects of your first Stress level.",
    },
    {
        id: "THINK_YOUR_WAY_OUT",
        name: "Think Your Way Out",
        tier: 4,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You can use points from your Intellect Pool rather than your Might Pool or Speed Pool on any noncombat action.",
    },
    {
        id: "CYPHER_MANIFESTATION",
        name: "Cypher Manifestation",
        tier: 4,
        cost: "4 Might points and 3 Stress",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You transform one cypher that you currently have into a small physical object a person could hold in their hand. You can then give that object to another person for them to use. It counts against their cypher limit.",
    },
    {
        id: "EDIT_MEMORIES",
        name: "Edit Memories",
        tier: 4,
        cost: "4 Intellect points and 3 Stress",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You reach into the mind of a person within immediate range and edit the last five minutes of their memory. For example, you could make someone on guard forget they ever saw you pass by, misremember a code they just learned, or believe a different person pushed them down than who actually did.",
    },
    {
        id: "SEE_THE_TRUTH",
        name: "See the Truth",
        tier: 5,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You see through magical disguises, veils, illusions, and similar obfuscations, with no roll needed. Beware, though: sometimes the truth might be dangerous, with revelations leading to Stress.",
    },
    {
        id: "SKILL_WITH_ATTACKS",
        name: "Skill With Attacks",
        tier: 5,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "Choose one type of attack in which you are not already trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are trained in attacks using that type of weapon. You can select this ability multiple times. Each time you select it, you must choose a different type of attack.",
    },
    {
        id: "STERN_STUFF",
        name: "Stern Stuff",
        tier: 5,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You no longer suffer Stress from seeing something supernatural. All other stressful events still affect you, including using the supernatural.",
    },
    {
        id: "STRESSED_MIND",
        name: "Stressed Mind",
        tier: 5,
        cost: "4 Intellect points and 3 Stress",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "With a touch and a whisper, you give a creature such mind-spinning dread that they suffer 6 points of Stress (6 points of damage for an NPC).",
    },
    {
        id: "VANISH_FROM_SIGHT",
        name: "Vanish From Sight",
        tier: 5,
        cost: "5 Intellect points and 4 Stress",
        context: "Action to initiate.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You literally disappear, turning invisible for up to one minute. During this time, you can only move or gently manipulate objects (like open doors). If you do anything else, such as talk or attack, you reveal yourself as you do so. If this occurs, you can regain the remaining invisibility effect by taking an action to hide your position.",
    },
    {
        id: "CRAFT_ARTEFACT",
        name: "Craft Artefact",
        tier: 6,
        cost: " ",
        context: "Special",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "This ability allows for the creation of a single artefact. You can take this ability more than once to make multiple artefacts. The process is long, difficult, and confounding. You and the GM should work together to determine the particulars because every artefact is different. However, the creation process should involve:  • Plans, recipes, or instructions from a prior Avatar or occultist (or, alternatively, a dream or vision from one or more Entities) that are extremely difficult to obtain. • Cost in time in terms of months or even years, sometimes working steadily, sometimes with breaks for other activities. • Cost in money similar to an exorbitant item. • Cost in mental and/or physical well-being. Very likely 3 points of Stress gained during each day of the process, and a permanent loss of 3 points from your stat Pools. The finished artefact should create or produce a single effect equal to a sixth-tier ability from any type or focus, and the Stress cost of using it should be 3.",
    },
    {
        id: "DEFENDING_OTHERS",
        name: "Defending Others",
        tier: 6,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "Allies within an immediate distance ease their defenses against supernatural effects.",
    },
    {
        id: "MASTERY_WITH_DEFENSE",
        name: "Mastery With Defense",
        tier: 6,
        cost: " ",
        context: "Enabler.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "Choose one type of defense task in which you are trained: Might, Speed, or Intellect. You are specialized in defense tasks of that type. You can select this ability up to three times. Each time you select it, you must choose a different type of defense task.",
    },
    {
        id: "MEDITATIVE_RESTORATION",
        name: "Meditative Restoration",
        tier: 6,
        cost: "8 Intellect points",
        context: "Action to initiate.",
        supernatural: false,
        source: "type",
        type: "OCCULTIST",
        description: "You rid yourself of 3 points of Stress each minute you do nothing else.",
    },
    {
        id: "GHOST",
        name: "Ghost",
        tier: 6,
        cost: "6 Intellect points and 5 Stress",
        context: "Action to initiate.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "For the next ten minutes, you gain an asset to sneaking tasks. During this time, you can move through solid barriers at a rate of 1 foot (30 cm) per round, and you can perceive while phased within a barrier or object, which allows you to peek through walls.",
    },
    {
        id: "PSYCHOKINETIC_ATTACK",
        name: "Psychokinetic Attack",
        tier: 6,
        cost: "6 Might points and 5 Stress",
        context: "Action.",
        supernatural: true,
        source: "type",
        type: "OCCULTIST",
        description: "You can use this attack in one of two ways. The first is to pick up a heavy object and hurl it at someone within short range. This attack is an Intellect action, and if successful, it deals 6 points of damage to the target and to the hurled object (which could be another foe, although that would require two rolls—one roll to grab the first foe and another roll to hit the second foe with the first). The second way to use this attack is to unleash a shattering burst of power that works only against an inanimate object no larger than half your size. Make an Intellect roll to instantly destroy the object; the task is eased by three steps compared to breaking it with brute strength.",
    },
]